### ISSUE TITLE
能否支持自定义 /var/lib/sealer/ /var/lib/docker/ 的路径

### ISSUE THREAD

**Issue by jelly320** [sealerio/sealer#1017]
## Issue Description

Type: *feature request*

### Describe what feature you want
装机环境有限制，能否支持自定义 /var/lib/sealer/ /var/lib/docker/ 的路径

**Comment by kakaZhou719** [comment]
@jelly320 ，Currently we do not support this feature, but we may do it in the future。

**Comment by allencloud** [comment]
duplicated, closing
