### ISSUE TITLE
support to change sealer root directory /var/lib/sealer to another location

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1114]
## Issue Description

By default, sealer stores most of its data inside the /var/lib/sealer directory on Linux systems. There may come a time when user want to move this storage space to a new location. 

For example, the most obvious reason might be that running out of disk space.

so , we could support user to config the sealer root dir. 

Type: *feature request*

**Comment by fanux** [comment]
User how to use it? env: `SEALER_DATA_DIT=/data/seaer`?

**Comment by kakaZhou719** [comment]
> User how to use it? env: `SEALER_DATA_DIT=/data/seaer`?

Env will lost when shell restart. It's better to put it in the user's home directory ：$HOME/.sealer.json。

**Comment by sfeng1996** [comment]
> > User how to use it? env: `SEALER_DATA_DIT=/data/seaer`?
> 
> Env will lost when shell restart. It's better to put it in the user's home directory ：$HOME/.sealer.json。

hi，Is this function module scheduled for implementation? If so, when?
