### ISSUE TITLE
[github-actions] auto-build kuberentes base ClusterImage

### ISSUE THREAD

**Issue by Stevent-fei** [sealerio/sealer#1242]
If you want to build the image you want, you can comment on /imagebuild k8sversion
eg:/imagebuild v1.20.14
![image](https://user-images.githubusercontent.com/69408038/162114079-e13e3bd3-6b34-49b8-9b23-32d9c512fab0.png)

- Docker is used for images below k8s v1.20, and containerd is used for images of v1.24 and above: 
`/imagebuild ${version}`
- There are two CRI types supported in the k8s [v1.20-v1.24.0) version: [ docker | containerd ]: `
/imagebuild ${version} ${cri}`

**Comment by laowenyi** [comment]
> If you want to build the image you want, you can comment on /imagebuild k8sversion eg:/imagebuild v1.20.14 ![image](https://user-images.githubusercontent.com/69408038/162114079-e13e3bd3-6b34-49b8-9b23-32d9c512fab0.png)
> 
> After successful construction, included calico image name : kubernetes:v1.20.14 Not included calico image : kubernetes:v1.20.14-alpine

/imagebuild v1.23.0 arm64

**Comment by kakaZhou719** [comment]
Temporarily closed for enhancing and stabilizing the core function. we are plan to reopen it with more cluster runtime supported like k0s, k3s at late October.  if you want anther kubernetes version see `https://github.com/sealerio/basefs` to build it manually, feel free to contact us if you have any questions.
