### ISSUE TITLE
deploy mysql occur err

### ISSUE THREAD

**Issue by fanspace** [sealerio/sealer#1285]
![1](https://user-images.githubusercontent.com/14883295/161208343-84a8d585-1b87-4661-aa2f-0e37d5e97122.png)
![2](https://user-images.githubusercontent.com/14883295/161208358-3e1408bb-e197-44e3-b9d4-622c4c6fb2a8.png)
![3](https://user-images.githubusercontent.com/14883295/161208373-89b97d9d-e699-4bdc-8577-80b1b3733cb8.png)

#### Environment:

- sealer version (use `sealer version`): 0.7.1
- Cloud provider or hardware configuration:  vm
- OS (e.g: `cat /etc/os-release`): ubuntu 20
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@fanspace,whats your cloud image name ? sealer official cloud image have not been updated since 0.6.1 , We recommend rebuilding one based on the corresponding kubefile.

**Comment by fanspace** [comment]
> @fanspace,whats your cloud image name ? sealer official cloud image have not been updated since 0.6.1 , We recommend rebuilding one based on the corresponding kubefile.

hi, thanks for u reply,  i build k8s cluster via:
wget https://sealer.oss-cn-beijing.aliyuncs.com/sealers/sealer-v0.7.1-linux-amd64.tar.gz --no-check-certificate && \
tar zxvf sealer-v0.7.1-linux-amd64.tar.gz && mv sealer /usr/bin

**Comment by kakaZhou719** [comment]
@fanspace , as my advice ,you could use the latest sealer version  : 0.8.3, and rebuilt the mysql cloud image to run.  FYI: http://sealer.cool/docs/getting-started/build-cloudimage.html#build-type
