### ISSUE TITLE
When sealer is deployed, registry is render as sea.hub:5000

### ISSUE THREAD

**Issue by Stevent-fei** [sealerio/sealer#1380]
Change sealer registryurl to public cloud URL,When sealer is deployed, registry is render as sea.hub:5000
![image](https://user-images.githubusercontent.com/65949637/167388246-f9d27faa-0562-4fcd-a814-458fe9014704.png)

**Comment by Stevent-fei** [comment]
![image](https://user-images.githubusercontent.com/65949637/167526258-dba59f68-18cf-47ba-9179-3881a9ea9d34.png)

**Comment by lllwan** [comment]
I understand that you should customize the domain name of registry. This can be achieved through the config function. You can refer to: http://sealer.cool/docs/getting-started/config.html#overwrite-configuration
For example:
`
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: registry_domain_config
spec:
  strategy: merge
    path: etc/registry.yml
    data: |
    domain: youdomain.com
    port: "5000"
`
