### ISSUE TITLE
same Clusterfile failed installation on different OS distribution(Rocky Linux release 8.5 (Green Obsidian))

### ISSUE THREAD

**Issue by laowenyi** [sealerio/sealer#1396]
同样的clusterfile 
在 Rocky Linux release 8.5 (Green Obsidian) 版本安装失败
在CentOS Linux release 7.9.2009 (Core) 上安装成功
#### What happened:

在Rocky Linux release 8.5 (Green Obsidian) 上我们发现大量的日志
 "Error getting node" err="node \"master0\" not found"
#### What you expected to happen:
我们ping一下master0
[root@localhost ~]# ping master0
PING master0(master0 (fe80::fcfc:feff:fef5:1231%ens18)) 56 data bytes
64 bytes from master0 (fe80::fcfc:feff:fef5:1231%ens18): icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from master0 (fe80::fcfc:feff:fef5:1231%ens18): icmp_seq=2 ttl=64 time=0.060 ms
64 bytes from master0 (fe80::fcfc:feff:fef5:1231%ens18): icmp_seq=3 ttl=64 time=0.065 ms

然后在 CentOS Linux release 7.9.2009 (Core) 上，我们ping 一下master
PING master (10.244.158.112) 56(84) bytes of data.
64 bytes from sea.hub (10.244.158.112): icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from sea.hub (10.244.158.112): icmp_seq=2 ttl=64 time=0.072 ms
64 bytes from sea.hub (10.244.158.112): icmp_seq=3 ttl=64 time=0.052 ms
#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
- Kernel (e.g. `uname -a`): 4.18.0-348.el8.0.2.x86_64
- Install tools:
- Others:

**Comment by laowenyi** [comment]
/etc/kubernetes/kubelet.conf 里面的内容
contexts:
- context:
    cluster: kubernetes
    user: system:node:master0
  name: system:node:master0@kubernetes
current-context: system:node:master0@kubernetes

**Comment by laowenyi** [comment]
> 同样的clusterfile 在 Rocky Linux release 8.5 (Green Obsidian) 版本安装失败 在CentOS Linux release 7.9.2009 (Core) 上安装成功
> 
> #### What happened:
> 在Rocky Linux release 8.5 (Green Obsidian) 上我们发现大量的日志 "Error getting node" err="node "master0" not found"
> 
> #### What you expected to happen:
> 我们ping一下master0 [root@localhost ~]# ping master0 PING master0(master0 (fe80::fcfc:feff:fef5:1231%ens18)) 56 data bytes 64 bytes from master0 (fe80::fcfc:feff:fef5:1231%ens18): icmp_seq=1 ttl=64 time=0.044 ms 64 bytes from master0 (fe80::fcfc:feff:fef5:1231%ens18): icmp_seq=2 ttl=64 time=0.060 ms 64 bytes from master0 (fe80::fcfc:feff:fef5:1231%ens18): icmp_seq=3 ttl=64 time=0.065 ms
> 
> 然后在 CentOS Linux release 7.9.2009 (Core) 上，我们ping 一下master PING master (10.244.158.112) 56(84) bytes of data. 64 bytes from sea.hub (10.244.158.112): icmp_seq=1 ttl=64 time=0.049 ms 64 bytes from sea.hub (10.244.158.112): icmp_seq=2 ttl=64 time=0.072 ms 64 bytes from sea.hub (10.244.158.112): icmp_seq=3 ttl=64 time=0.052 ms
> 
> #### How to reproduce it (as minimally and precisely as possible):
Clusterfile

apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: default-kubernetes-cluster
spec:
  image: kubernetes:v1.23.0
  ssh:
    passwd: 123456
  hosts:
    - ips: [ 10.244.156.208 ]
      roles: [ master ]
    - ips: [ 10.244.156.209]
      roles: [ node ]
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: MyHostname
spec:
  type: HOSTNAME
  action: PreInit
  data: |
    10.244.156.208 master0
    10.244.156.209 node-1

---
apiVersion: sealer.cloud/v2
kind: Plugin
metadata:
  name: SHELL
spec:
  type: SHELL
  action: PostInstall
  'on': master
  data: |
     mkdir -p /tmp/master
---
apiVersion: sealer.cloud/v2
kind: Plugin
metadata:
  name: SHELL
spec:
  type: SHELL
  action: PostInstall
  'on': node
  data: |
     mkdir -p /tmp/woker

> #### Anything else we need to know?:
> #### Environment:
> * sealer version (use `sealer version`):
v0.8.5
> * Cloud provider or hardware configuration:
> * OS (e.g: `cat /etc/os-release`):
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
> * Kernel (e.g. `uname -a`):
> * Install tools:
> * Others:

**Comment by allencloud** [comment]
Thanks for your feedback. @laowenyi 

I think this is an operating system distribution compatibility issue. Actually, I have to say we have not done the compatibility of Rocky Linux release 8.5 (Green Obsidian). But of course, we should make efforts to support it.

Back to the issue above, should you paste more logs about the error sealer throws. Currently, we only see `"Error getting node" err="node "master0" not found"` . In addition, what is the kernel version of `uanme -r` ?

**Comment by laowenyi** [comment]
> 

4.18.0-348.el8.0.2.x86_64

**Comment by laowenyi** [comment]
有没有兼容性列表

**Comment by allencloud** [comment]
> 有没有兼容性列表

I afraid that we have not. But from now on, I think we should maintain a OS-compatibility list.

**Comment by laowenyi** [comment]
> 

那么我这个版本的问题要怎么去解决，我们准备拿这个版本的系统去交付的，这样的话我们sealer 就没法上了

**Comment by allencloud** [comment]
> > 
> 
> 那么我这个版本的问题要怎么去解决，我们准备拿这个版本的系统去交付的，这样的话我们sealer 就没法上了

 @laowenyi  We can move on only after seeing what error happens in your environment. Currently you just tell us you ran into issues. But could provide more error information. You can download that into a log.txt file and attach that to this issue.

**Comment by laowenyi** [comment]
2022-05-13 21:31:30 [INFO] [local.go:288] Start to create a new cluster: master [10.244.156.208], worker [10.244.156.209]
copying files to 10.244.156.209: 32/32
2022-05-13 21:32:32 [INFO] [hostname_plugin.go:89] successfully changed node 10.244.156.208 hostname to master0.
2022-05-13 21:32:32 [INFO] [hostname_plugin.go:89] successfully changed node 10.244.156.209 hostname to node-1.
2022-05-13 21:32:33 [INFO] [kube_certs.go:234] APIserver altNames :  {map[apiserver.cluster.local:apiserver.cluster.local kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost master0:master0] map[10.103.97.2:10.103.97.2 10.244.156.208:10.244.156.208 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1 172.16.0.181:172.16.0.181]}
2022-05-13 21:32:33 [INFO] [kube_certs.go:254] Etcd altnames : {map[localhost:localhost master0:master0] map[10.244.156.208:10.244.156.208 127.0.0.1:127.0.0.1 ::1:::1]}, commonName : master0
2022-05-13 21:32:37 [INFO] [kubeconfig.go:267] [kubeconfig] Writing "admin.conf" kubeconfig file

2022-05-13 21:32:38 [INFO] [kubeconfig.go:267] [kubeconfig] Writing "controller-manager.conf" kubeconfig file

2022-05-13 21:32:38 [INFO] [kubeconfig.go:267] [kubeconfig] Writing "scheduler.conf" kubeconfig file

2022-05-13 21:32:38 [INFO] [kubeconfig.go:267] [kubeconfig] Writing "kubelet.conf" kubeconfig file

++ dirname init-registry.sh
+ cd .
+ REGISTRY_PORT=5000
+ VOLUME=/var/lib/sealer/data/default-kubernetes-cluster/rootfs/registry
+ REGISTRY_DOMAIN=sea.hub
+ container=sealer-registry
+++ pwd
++ dirname /var/lib/sealer/data/default-kubernetes-cluster/rootfs/scripts
+ rootfs=/var/lib/sealer/data/default-kubernetes-cluster/rootfs
+ config=/var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_config.yml
+ htpasswd=/var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_htpasswd
+ certs_dir=/var/lib/sealer/data/default-kubernetes-cluster/rootfs/certs
+ image_dir=/var/lib/sealer/data/default-kubernetes-cluster/rootfs/images
+ mkdir -p /var/lib/sealer/data/default-kubernetes-cluster/rootfs/registry
+ load_images
+ for image in "$image_dir"/*
+ '[' -f /var/lib/sealer/data/default-kubernetes-cluster/rootfs/images/registry.tar ']'
+ docker load -q -i /var/lib/sealer/data/default-kubernetes-cluster/rootfs/images/registry.tar
Loaded image: registry:2.7.1
++ docker ps -aq -f name=sealer-registry
+ '[' '' ']'
+ regArgs='-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key'
+ '[' -f /var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_config.yml ']'
+ sed -i s/5000/5000/g /var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_config.yml
+ regArgs='-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key     -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml'
+ '[' -f /var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_htpasswd ']'
+ docker run -d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key -v /var/lib/sealer/data/default-kubernetes-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml registry:2.7.1
a2debea8ddcc416aae59aca938cd0d5acda75a402c2be60754ff71192bba5385
+ check_registry
+ n=1
+ ((  n <= 3  ))
++ docker inspect --format '{{json .State.Status}}' sealer-registry
+ registry_status='"running"'
+ [[ "running" == \"running\" ]]
+ break
2022-05-13 21:32:46 [INFO] [init.go:251] start to init master0...
W0513 21:32:46.647668  349635 strict.go:55] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "type"
[init] Using Kubernetes version: v1.23.0
[preflight] Running pre-flight checks
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "master0" could not be reached
        [WARNING Hostname]: hostname "master0": lookup master0 on [::1]:53: read udp [::1]:55795->[::1]:53: read: connection refused
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
W0513 21:32:48.461531  349635 kubeconfig.go:249] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has an unexpected API Server URL: expected: https://10.244.156.208:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
W0513 21:32:48.806797  349635 kubeconfig.go:249] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has an unexpected API Server URL: expected: https://10.244.156.208:6443, got: https://apiserver.cluster.local:6443
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/scheduler.conf"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in docker:
                - 'docker ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
Error: failed to init master0 init master0 failed, error: exit status 1. Please clean and reinstall
Usage:
  sealer apply [flags]

Examples:
sealer apply -f Clusterfile

Flags:
  -f, --Clusterfile string   apply a kubernetes cluster (default "Clusterfile")
      --force                We also can input an --force flag to delete cluster by force
  -h, --help                 help for apply

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode
      --hide-path       hide the log path
      --hide-time       hide the log time

failed to init master0 init master0 failed, error: exit status 1. Please clean and reinstall

**Comment by laowenyi** [comment]
May 13 23:59:34 master0 kubelet[349834]: E0513 23:59:34.646458  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:34 master0 kubelet[349834]: E0513 23:59:34.747367  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:34 master0 kubelet[349834]: E0513 23:59:34.848247  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:34 master0 kubelet[349834]: I0513 23:59:34.937884  349834 kubelet_node_status.go:70] "Attempting to register node" node="master0"
May 13 23:59:34 master0 kubelet[349834]: E0513 23:59:34.938556  349834 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6443/ap>
May 13 23:59:34 master0 kubelet[349834]: E0513 23:59:34.948744  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.049815  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.151078  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.251468  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.351634  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.452699  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.553013  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.653458  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.753623  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.854492  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:35 master0 kubelet[349834]: E0513 23:59:35.954629  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.055606  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.156032  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: I0513 23:59:36.220585  349834 cni.go:240] "Unable to update cni config" err="no networks found in /etc/cni/net.d"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.257073  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.332670  349834 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{N>
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.358317  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.361443  349834 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/api>
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.458772  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.559902  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.656023  349834 kubelet.go:2347] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady mes>
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.660305  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.761477  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.862097  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:36 master0 kubelet[349834]: E0513 23:59:36.963230  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:37 master0 kubelet[349834]: E0513 23:59:37.064015  349834 kubelet.go:2422] "Error getting node" err="node \"master0\" not found"
May 13 23:59:37 master0 kubelet[349834]: E0513 23:59:37.119228  349834 kuberuntime_sandbox.go:43] "Failed to generate sandbox config for pod" err="open /etc/resolv.conf: no such file or direc>
May 13 23:59:37 master0 kubelet[349834]: E0513 23:59:37.119264  349834 kuberuntime_manager.go:832] "CreatePodSandbox for pod failed" err="open /etc/resolv.conf: no such file or directory" pod>
May 13 23:59:37 master0 kubelet[349834]: E0513 23:59:37.119308  349834 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-master0_kube->
l

**Comment by allencloud** [comment]
In the installing log, I found the log of `[preflight]` , but I have not found any preflight related code in sealer repo, or even sealerio org. 

So I am curious where are these `preflight` code from? @fanux @kakaZhou719 @bxy4543 
sealer version is v0.8.5.

**Comment by kakaZhou719** [comment]
@allencloud ,`preflight` logs comes from `kubeadm init` 。 @laowenyi ，kubelet use default  "/etc/resolv.conf" for the container DNS resolution configuration, you can set this value by add this to your clusterfile:

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
resolvConf: {your resolv config path}
```

**Comment by fanux** [comment]
```
 error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "type"
```

I think the error is cause by kubeadm config, sealer support kernel 4+ ~ 5-

**Comment by laowenyi** [comment]
> @allencloud ,`preflight` logs comes from `kubeadm init` 。 @laowenyi ，kubelet use default "/etc/resolv.conf" for the container DNS resolution configuration, you can set this value by add this to your clusterfile:
> 
> ```yaml
> apiVersion: kubelet.config.k8s.io/v1beta1
> kind: KubeletConfiguration
> resolvConf: {your resolv config path}
> ```

fix success
