### ISSUE TITLE
Support for installing Kubernetes using non-root accounts with sudo

### ISSUE THREAD

**Issue by yanruogu** [sealerio/sealer#1402]
## Issue Description

Type: *feature request*

### Describe what feature you want

Support for installing Kubernetes using non-root accounts with sudo

### Additional context

The server root account provided by our customer is disabled, but can be used as a normal user to claim rights through Sudo

**Comment by allencloud** [comment]
@kakaZhou719 Is this feature already supported in main branch or latest version of sealer?

**Comment by kakaZhou719** [comment]
@yanruogu @allencloud , we are not support this feature yet, but will do it at the next version.

**Comment by yanruogu** [comment]
OK，thank you! @kakaZhou719

**Comment by tanxiaoning007** [comment]
When installing an environment with non-root user, I think we only need to wrap the command into the sudo /bin/sh shell.
