### ISSUE TITLE
sealer pull: 拉取阿里云镜像仓库的镜像失败

### ISSUE THREAD

**Issue by huangjun0210** [sealerio/sealer#1410]
#### What happened:

[root@k8s-node03 .sealer]# sealer pull registry.cn-hangzhou.aliyuncs.com/huangjun0210/kubernetes:v1.19.16
Start to Pull Image registry.cn-hangzhou.aliyuncs.com/huangjun0210/kubernetes:v1.19.16
Error: get digest error: get digest from manifest list error: no manifest of the corresponding platform
Usage:
  sealer pull [flags]

Examples:
sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8

Flags:
  -h, --help              help for pull
      --platform string   set cloud image platform

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode
      --hide-path       hide the log path
      --hide-time       hide the log time

get digest error: get digest from manifest list error: no manifest of the corresponding platform

![image](https://user-images.githubusercontent.com/26295600/168720252-fe19ff55-0572-4d38-86e8-022b3887b799.png)

![image](https://user-images.githubusercontent.com/26295600/168720307-91302f91-63f7-4f1a-81ac-d732afeaac44.png)

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):4.19.12-1.el7.elrepo.x86_64
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@huangjun0210,pls update the Environment section, like your sealer version, and your image `registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8` build version
