### ISSUE TITLE
sealer run之后delete没有删除干净，报错address already in use: unknown

### ISSUE THREAD

**Issue by jiuquguiyu** [sealerio/sealer#1411]
sealer run 执行之后，集群报错，有一个服务端口有问题。
然后修改yaml文件端口，继续sealer run，提示集群存在。
执行sealer delete -f /root/.sealer/my-cluster/Clusterfile 去清理集群
然后再次执行sealer run ，报错：
attempt to start registry
+ docker start sealer-registry
Error response from daemon: failed to listen to abstract unix socket "/containerd-shim/moby/02b7087c0a31a2cca6669325c2e3a9c4e190f554b27dfecee9c32d388e1ac710/shim.sock": listen unix /containerd-shim/moby/02b7087c0a31a2cca6669325c2e3a9c4e190f554b27dfecee9c32d388e1ac710/shim.sock: bind: address already in use: unknown
Error: failed to start containers: sealer-registry
Error: failed to init master0 failed to execute command(cd /var/lib/sealer/data/my-cluster/rootfs/scripts && sh init-registry.sh 5000 /var/lib/sealer/data/my-cluster/rootfs/registry sea.hub) on host(xxx): error(exit status 1)

**Comment by bxy4543** [comment]
It looks like the registry is not being cleaned up on clean.
Execute the `docker rm -f sealer-registry` command to clean up.

**Comment by jiuquguiyu** [comment]
[ sealer]# docker rm -f sealer-registry
sealer-registry
[ sealer]# sealer run iregistry.baidu-int.com/acg-det-tian/flinksp-mysql:0.0.2 --masters ip
2022-05-17 14:27:18 [INFO] [local.go:288] Start to create a new cluster: master [ip], worker []
2022-05-17 14:27:22 [INFO] [kube_certs.go:234] APIserver altNames :  {map[apiserver.cluster.local:apiserver.cluster.local  kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost] map[10.103.97.2:10.103.97.2 10.187.33.14:10.187.33.14 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1 172.16.0.181:172.16.0.181]}
2022-05-17 14:27:22 [INFO] [kube_certs.go:254] Etcd altnames : {map[ localhost:localhost] map[10.187.33.14:10.187.33.14 127.0.0.1:127.0.0.1 ::1:::1]}, commonName :xxx
2022-05-17 14:27:22 [INFO] [kube_certs.go:262] sa.key sa.pub already exist
2022-05-17 14:27:25 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/admin.conf"

2022-05-17 14:27:25 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/controller-manager.conf"

2022-05-17 14:27:26 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/scheduler.conf"

2022-05-17 14:27:26 [INFO] [kubeconfig.go:277] [kubeconfig] Using existing kubeconfig file: "/var/lib/sealer/data/my-cluster/kubelet.conf"

++ dirname init-registry.sh
+ cd .
+ REGISTRY_PORT=5000
+ VOLUME=/var/lib/sealer/data/my-cluster/rootfs/registry
+ REGISTRY_DOMAIN=sea.hub
+ container=sealer-registry
+++ pwd
++ dirname /var/lib/sealer/data/my-cluster/rootfs/scripts
+ rootfs=/var/lib/sealer/data/my-cluster/rootfs
+ config=/var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml
+ htpasswd=/var/lib/sealer/data/my-cluster/rootfs/etc/registry_htpasswd
+ certs_dir=/var/lib/sealer/data/my-cluster/rootfs/certs
+ image_dir=/var/lib/sealer/data/my-cluster/rootfs/images
+ mkdir -p /var/lib/sealer/data/my-cluster/rootfs/registry
+ load_images
+ for image in '"$image_dir"/*'
+ '[' -f /var/lib/sealer/data/my-cluster/rootfs/images/registry.tar ']'
+ docker load -q -i /var/lib/sealer/data/my-cluster/rootfs/images/registry.tar
Loaded image: registry:2.7.1
++ docker ps -aq -f name=sealer-registry
+ '[' '' ']'
+ regArgs='-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key'
+ '[' -f /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml ']'
+ sed -i s/5000/5000/g /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml
+ regArgs='-d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key     -v /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml'
+ '[' -f /var/lib/sealer/data/my-cluster/rootfs/etc/registry_htpasswd ']'
+ docker run -d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key -v /var/lib/sealer/data/my-cluster/rootfs/etc/registry_config.yml:/etc/docker/registry/config.yml registry:2.7.1
f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e
docker: Error response from daemon: no status provided on response: unknown.
+ startRegistry
+ n=1
+ ((  n <= 3  ))
+ echo 'attempt to start registry'
attempt to start registry
+ docker start sealer-registry
Error response from daemon: failed to listen to abstract unix socket "/containerd-shim/moby/f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e/shim.sock": listen unix /containerd-shim/moby/f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e/shim.sock: bind: address already in use: unknown
Error: failed to start containers: sealer-registry
+ ((  n < 3 ))
+ ((  n++  ))
+ sleep 3
+ ((  n <= 3  ))
+ echo 'attempt to start registry'
attempt to start registry
+ docker start sealer-registry
Error response from daemon: failed to listen to abstract unix socket "/containerd-shim/moby/f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e/shim.sock": listen unix /containerd-shim/moby/f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e/shim.sock: bind: address already in use: unknown
Error: failed to start containers: sealer-registry
+ ((  n < 3 ))
+ ((  n++  ))
+ sleep 3
+ ((  n <= 3  ))
+ echo 'attempt to start registry'
attempt to start registry
+ docker start sealer-registry
Error response from daemon: failed to listen to abstract unix socket "/containerd-shim/moby/f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e/shim.sock": listen unix /containerd-shim/moby/f670fac7f0195fda6e3d5ac2085c3dec4646cc834c38acbca0d94d21f6f12b8e/shim.sock: bind: address already in use: unknown
Error: failed to start containers: sealer-registry
+ ((  n < 3 ))
Error: failed to init master0 failed to execute command(cd /var/lib/sealer/data/my-cluster/rootfs/scripts && sh init-registry.sh 5000 /var/lib/sealer/data/my-cluster/rootfs/registry sea.hub) on host(ip): error(exit status 1)
Usage:
  sealer run [flags]

Examples:

create cluster to your bare metal server, appoint the iplist:
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
		--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx

specify server SSH port :
  All servers use the same SSH port (default port: 22)：
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --port 24 --passwd xxx

  Different SSH port numbers exist：
	sealer run kubernetes:v1.19.8 --masters 192.168.0.2,192.168.0.3:23,192.168.0.4:24 \
	--nodes 192.168.0.5:25,192.168.0.6:25,192.168.0.7:27 --passwd xxx

create a cluster with custom environment variables:
	sealer run -e DashBoardPort=8443 mydashboard:latest  --masters 192.168.0.2,192.168.0.3,192.168.0.4 \
	--nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx


Flags:
      --cluster-name string   set cluster name (default "my-cluster")
      --cmd-args strings      set args for image cmd instruction
  -e, --env strings           set custom environment variables
  -h, --help                  help for run
  -m, --masters string        set Count or IPList to masters
  -n, --nodes string          set Count or IPList to nodes
  -p, --passwd string         set cloud provider or baremetal server password
      --pk string             set baremetal server private key (default "/root/.ssh/id_rsa")
      --pk-passwd string      set baremetal server private key password
      --port uint16           set the sshd service port number for the server (default port: 22) (default 22)
      --provider ALI_CLOUD    set infra provider, example ALI_CLOUD, the local server need ignore this
  -u, --user string           set baremetal server username (default "root")

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode
      --hide-path       hide the log path
      --hide-time       hide the log time

failed to init master0 failed to execute command(cd /var/lib/sealer/data/my-cluster/rootfs/scripts && sh init-registry.sh 5000 /var/lib/sealer/data/my-cluster/rootfs/registry sea.hub) on host(ip): error(exit status 1)

**Comment by bxy4543** [comment]
what is the docker version？ @jiuquguiyu

**Comment by jiuquguiyu** [comment]
Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15

**Comment by bxy4543** [comment]
I found some similar [questions](https://github.com/docker/for-linux/issues/813), you can try to upgrade the containerd version.

**Comment by jiuquguiyu** [comment]
my containerd version is 
containerd:
Version: 1.2.6
GitCommit: 894b81a4b802e4eb2a91d1ce216b8817763c29fb

**Comment by jiuquguiyu** [comment]
update docker to 20.10.5 version success
