### ISSUE TITLE
Can't run when use new imageList registry

### ISSUE THREAD

**Issue by zhabinecho** [sealerio/sealer#1412]
```
2022-05-17 13:44:32 [INFO] [init.go:251] start to init master0...
W0517 13:44:32.532767   13383 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "shutdownGracePeriod"
W0517 13:44:32.574018   13383 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.8
[preflight] Running pre-flight checks
	[WARNING FileExisting-tc]: tc not found in system path
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image sea.hub:5000/kube-apiserver:v1.19.8: output: Error response from daemon: manifest for sea.hub:5000/kube-apiserver:v1.19.8 not found: manifest unknown: manifest unknown
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/kube-controller-manager:v1.19.8: output: Error response from daemon: manifest for sea.hub:5000/kube-controller-manager:v1.19.8 not found: manifest unknown: manifest unknown
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/kube-scheduler:v1.19.8: output: Error response from daemon: manifest for sea.hub:5000/kube-scheduler:v1.19.8 not found: manifest unknown: manifest unknown
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/kube-proxy:v1.19.8: output: Error response from daemon: manifest for sea.hub:5000/kube-proxy:v1.19.8 not found: manifest unknown: manifest unknown
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/pause:3.2: output: Error response from daemon: manifest for sea.hub:5000/pause:3.2 not found: manifest unknown: manifest unknown
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/etcd:3.4.13-0: output: Error response from daemon: manifest for sea.hub:5000/etcd:3.4.13-0 not found: manifest unknown: manifest unknown
, error: exit status 1
	[ERROR ImagePull]: failed to pull image sea.hub:5000/coredns:1.7.0: output: Error response from daemon: manifest for sea.hub:5000/coredns:1.7.0 not found: manifest unknown: manifest unknown
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
Error: failed to init master0 init master0 failed, error: exit status 1. Please clean and reinstall
```

#### What happened:

Can't run when  use the self-making kubernetes images

#### How to reproduce it (as minimally and precisely as possible):

          sudo wget https://sealer.oss-cn-beijing.aliyuncs.com/auto-build/context.tar.gz && sudo tar -zxf context.tar.gz && cd context
          #amd64
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl -o ./amd64/bin/kubectl
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/amd64/kubelet -o ./amd64/bin/kubelet
          sudo curl -L https://dl.k8s.io/release/$version/bin/linux/amd64/kubeadm -o ./amd64/bin/kubeadm
          sudo wget https://sealer.oss-cn-beijing.aliyuncs.com/sealer-latest.tar.gz && sudo tar -xvf sealer-latest.tar.gz -C /usr/bin
          sudo sealer login ${{secrets.PRIVATEWAREHOUSE}}
          sudo sed -i "s/v1.19.8/$version/g" ./rootfs/etc/kubeadm.yml && sudo sed -i "s/v1.19.8/$version/g" ./calico/Kubefile
          sudo chmod +x ./amd64/bin/kubeadm && sudo ./amd64/bin/kubeadm config images list --config ./rootfs/etc/kubeadm.yml
          sudo ./amd64/bin/kubeadm config images list --config ./rootfs/etc/kubeadm.yml 2>/dev/null>> imageList
          if [ $(sudo ./amd64/bin/kubeadm config images list --config ./rootfs/etc/kubeadm.yml 2>/dev/null |grep -c "coredns/coredns") -gt 0 ]; then sudo sed -i "s/#imageRepository/imageRepository/g" ./rootfs/etc/kubeadm.yml; fi
          sudo sed -i "s/k8s.gcr.io/sea.hub:5000/g" ./rootfs/etc/kubeadm.yml
         
         Modify the imageList registry instead of k8s.gcr.io:
         fanux/lvscare:latest
         registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.19.8
         registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.19.8
         registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.19.8
         registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.19.8
         registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
         registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.13-0
         registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.7.0

          sudo sealer build -t kubernetes:$version-alpine --platform linux/arm64,linux/amd64

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhabinecho** [comment]
[root]# sealer inspect kubernetes:v1.19.8-alpine
- kind: Image
  metadata:
    annotations:
      sea.aliyun.com/ClusterFile: |
        apiVersion: sealer.cloud/v2
        kind: Cluster
        metadata:
          creationTimestamp: null
          name: my-cluster
        spec:
          image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8-alpine
          ssh:
            port: "22"
            user: root
        status: {}
    creationTimestamp: null
    name: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8-alpine
  spec:
    id: 0f95c26d4caf3ec6ddbd1a0ddeb7f046c9225e9f668a00c6a7900f3c970ba0a0
    image_config:
      args: {}
      cmd: {}
    layers:
    - id: sha256:8312d7710aa9173f4fe0494f706df77a5858c064f1a599201529c6ee21841528
      type: COPY
      value: rootfs/* .
    - id: sha256:21ca3bfbd98c9dcfb2291a187cfe759ff239a29872c9b8b96a5cf8461ff05ed7
      type: COPY
      value: ${ARCH}/* .
    - id: sha256:d9e0c53185d3c51e4e59a5da921137007920e7bfbbd98527148f7e056d91a7dd
      type: COPY
      value: imageList manifests
    - id: sha256:1894832c0300a30c7467640845b4d0d837ec059e630c5e3fc8a47320e2242407
      type: BASE
      value: rootfs cache
    platform:
      architecture: arm64
      os: linux
      variant: v8
    sealer_version: v0.8.5
  status: {}
- kind: Image
  metadata:
    annotations:
      sea.aliyun.com/ClusterFile: |
        apiVersion: sealer.cloud/v2
        kind: Cluster
        metadata:
          creationTimestamp: null
          name: my-cluster
        spec:
          image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8-alpine
          ssh:
            port: "22"
            user: root
        status: {}
    creationTimestamp: null
    name: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8-alpine
  spec:
    id: 88f0659403b7f6ad4d5cd758cc2b259b141e36ef4115a16c0b3b90dc54b9d399
    image_config:
      args: {}
      cmd: {}
    layers:
    - id: sha256:8312d7710aa9173f4fe0494f706df77a5858c064f1a599201529c6ee21841528
      type: COPY
      value: rootfs/* .
    - id: sha256:d6983cf179eeb2a2dba7a862847d7c20ececdfaeb54d633382a88041714033c5
      type: COPY
      value: ${ARCH}/* .
    - id: sha256:80d6dc88e50598843a0654554ce4d1d25928cea50a8c9bc961d66d72d220a21a
      type: COPY
      value: imageList manifests
    - id: sha256:dc3d249e7550535f15fa34eb8ac2fd49abf10b6034b58744b2c8fb46159f8941
      type: BASE
      value: rootfs cache
    platform:
      architecture: amd64
      os: linux
    sealer_version: v0.8.5
  status: {}

**Comment by zhabinecho** [comment]
[root]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
033dd9e2732d        registry:2.7.1      "/entrypoint.sh /etc…"   21 minutes ago      Up 21 minutes                           sealer-registry

**Comment by kakaZhou719** [comment]
@zhabinecho ,pls try `sudo sed -i "s/k8s.gcr.io/sea.hub:5000\/google_containers/g" ./rootfs/etc/kubeadm.yml` thats because k8s base images from your imageList with repo.
