### ISSUE TITLE
Support cluster preflight tool

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1417]
## Issue Description

Type: *feature request*

### Describe what feature you want
Support cluster preflight tool, which can determine whether it can be successful before cluster deployment.
It can free user from tedious environmental checklists

**Comment by allencloud** [comment]
It is quite similar to https://github.com/sealerio/sealer/issues/1370. Shall we close this? @VinceCui

**Comment by VinceCui** [comment]
duplicate issue
