### ISSUE TITLE
Error "no default routes found"

### ISSUE THREAD

**Issue by qwtsc** [sealerio/sealer#1425]
#### What happened:
sealer run kubernetes:v1.19.8
error: failed to get default route ip, err: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"

#### What you expected to happen:

successfully install cluster
#### How to reproduce it (as minimally and precisely as possible):

ip route without default.
#ip route
1.1.1.0/30 dev tun0 proto kernel scope link src 1.1.1.1
10.0.0.0/8 via 11.158.174.55 dev bond0
11.0.0.0/8 via 11.158.174.55 dev bond0
11.158.174.0/26 dev bond0 proto kernel scope link src 11.158.174.31
30.0.0.0/8 via 11.158.174.55 dev bond0
33.0.0.0/8 via 11.158.174.55 dev bond0
100.64.0.0/10 via 11.158.174.55 dev bond0
169.254.0.0/16 dev bond0 scope link metric 1006
172.16.0.0/12 via 11.158.174.55 dev bond0
192.168.0.0/16 via 11.158.174.55 dev bond0

#### Anything else we need to know?:

see similar issue reported in [K3S](https://github.com/k3s-io/k3s/issues/1144)

#### Environment:

- sealer version (use `sealer version`): v0.8.5
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): 
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora anolis"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://os.alibaba-inc.com/"
BUG_REPORT_URL="https://os.alibaba-inc.com/"
- Kernel (e.g. `uname -a`): Linux nu2e07205.sqa.nu8 5.10.84-004.ali5000.alios7.x86_64
- Install tools: download tar && mv
- Others: nothing

**Comment by fanux** [comment]
add a default route to your host.

**Comment by qwtsc** [comment]
I do think it should be detected and added by sealer not by operator.
