### ISSUE TITLE
Info in sealer log file is incomplete

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1438]
#### What happened:
Info in sealer log file is incomplete.

When i run sealer command, it fails cause my image's bug, and stdout is complete, as this 

![image](https://user-images.githubusercontent.com/23137196/170006678-31f583c6-26f9-4aa0-be6d-10758e11b7d2.png)

but, when i want to see log in /var/lib/sealer/log, i find log is very short and simple, as this:

![image](https://user-images.githubusercontent.com/23137196/170006920-b54442a5-5dfc-492f-9a85-b6d540e36835.png)

#### What you expected to happen:
I think the log file is the most important info for debug, so it should save context as more as possible. File log should be in DEBUG mode.

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Actually log complete and readability is the matter that we should thoroughly improve. I think we should file an open issue to record the detailed log issue, and gradually tackle them with quite a lot of pull request. @VinceCui @fanux @kakaZhou719
