### ISSUE TITLE
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp x.x.x.x->8.8.8.8:53: i/o timeout

### ISSUE THREAD

**Issue by JasperDiShu** [sealerio/sealer#1442]
Description:
When running the default installation via the official helm chart of Bitnami kubeapps, some pods always crashed, investigate from related logs, it shows something wrong with the coredns. Need further support to investigate this issue.

#### What happened:
---kubectl get pod -nkubeapps
NAME                                                          READY   STATUS             RESTARTS   AGE
apprepo-kubeapps-sync-bitnami-1653528000-nf24k                0/1     CrashLoopBackOff   5          7m51s
kubeapps-79456c68c4-5kzkh                                     0/1     CrashLoopBackOff   136        12h
kubeapps-79456c68c4-xbhfc                                     0/1     CrashLoopBackOff   140        12h
kubeapps-internal-apprepository-controller-6776cf7ddf-m4wbz   1/1     Running            0          12h
kubeapps-internal-dashboard-6b7b9cd66-7588w                   1/1     Running            0          12h
kubeapps-internal-dashboard-6b7b9cd66-sxqth                   1/1     Running            0          12h
kubeapps-internal-kubeappsapis-d448977b-7h4bg                 1/1     Running            0          12h
kubeapps-internal-kubeappsapis-d448977b-tdt9h                 1/1     Running            0          12h
kubeapps-internal-kubeops-86f644c864-2pkx7                    1/1     Running            0          12h
kubeapps-internal-kubeops-86f644c864-znbn8                    1/1     Running            0          12h
kubeapps-postgresql-0                                         1/1     Running            0          12h

---kubectl logs -nkubeapps apprepo-kubeapps-sync-bitnami-1653528000-nf24k
I0526 01:26:23.690529       1 root.go:32] asset-syncer has been configured with: server.Config{DatabaseURL:"kubeapps-postgresql:5432", DatabaseName:"assets", DatabaseUser:"postgres", DatabasePassword:"JDdw4OqdGo", Debug:false, Namespace:"kubeapps", OciRepositories:[]string{}, TlsInsecureSkipVerify:false, FilterRules:"", PassCredentials:false, UserAgent:"asset-syncer/2.4.5 (kubeapps/2.4.5)", UserAgentComment:"kubeapps/2.4.5", GlobalReposNamespace:"kubeapps", KubeappsNamespace:"", AuthorizationHeader:"", DockerConfigJson:""}
Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp: lookup charts.bitnami.com on 10.96.0.10:53: read udp 100.124.207.244:54524->10.96.0.10:53: i/o timeout
Usage:
  asset-syncer sync [REPO NAME] [REPO URL] [REPO TYPE] [flags]

Flags:
  -h, --help                       help for sync
      --oci-repositories strings   List of OCI Repositories in case the type is OCI
      --version                    version for sync

Global Flags:
      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files
      --database-name string             Name of the database to use (default "charts")
      --database-url string              Database URL (default "localhost:5432")
      --database-user string             Database user
      --debug                            verbose logging
      --filter-rules string              JSON blob with the rules to filter assets
      --global-repos-namespace string    Namespace for global repos (default "kubeapps")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --namespace string                 Namespace of the repository being synced
      --one_output                       If true, only write logs to their native severity level (vs also writing to each lower severity level)
      --pass-credentials                 pass credentials to all domains
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --tls-insecure-skip-verify         Skip TLS verification
      --user-agent-comment string        UserAgent comment used during outbound requests
  -v, --v Level                          number for the log level verbosity (default 3)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Error: Error: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp: lookup charts.bitnami.com on 10.96.0.10:53: read udp 100.124.207.244:54524->10.96.0.10:53: i/o timeout

---kubectl logs -nkubeapps kubeapps-79456c68c4-5kzkh
nginx 01:30:01.67 
nginx 01:30:01.68 Welcome to the Bitnami nginx container
nginx 01:30:01.68 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
nginx 01:30:01.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nginx 01:30:01.71 
nginx 01:30:01.71 INFO  ==> ** Starting NGINX setup **
nginx 01:30:01.73 INFO  ==> Validating settings in NGINX_* env vars
nginx 01:30:01.81 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 01:30:01.82 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory
nginx 01:30:01.83 INFO  ==> ** NGINX setup finished! **

nginx 01:30:01.92 INFO  ==> ** Starting NGINX **
2022/05/26 01:30:01 [emerg] 1#1: host not found in upstream "kubeapps-internal-kubeappsapis" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:29
nginx: [emerg] host not found in upstream "kubeapps-internal-kubeappsapis" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:29

---kubectl logs -nkube-system coredns-86dfcb4f6f-gpwv9
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:42447->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:34748->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:41498->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:51833->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:54721->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:46312->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:59390->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:38924->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 kubeapps-internal-kubeappsapis. A: read udp 100.88.178.193:35052->8.8.8.8:53: i/o timeout

#### What you expected to happen:
All the CrashLoopBackOff pod can be status of Running normally.

#### Environment:

- sealer version (use `sealer version`):
---sealer version
{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

- Cloud provider or hardware configuration:
Alibaba Cloud

- OS (e.g: `cat /etc/os-release`):
---cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

- Kernel (e.g. `uname -a`):
---uname -a
Linux iZuf60ytt884ww7f8td9m4Z 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by fanux** [comment]
1. check the host can ping 8.8.8.8?
2. other pod can ping 8.8.8.8?
3. kubeapps has network policy?

**Comment by JasperDiShu** [comment]
> 1. check the host can ping 8.8.8.8?
> 2. other pod can ping 8.8.8.8?
> 3. kubeapps has network policy?

1/ The host can ping 8.8.8.8
2/no available pod that installed ping
3/no

**Comment by JasperDiShu** [comment]
Adding more info:
On the master:
[root@iZuf60ytt884ww7f8td9m4Z ~]# nslookup
> server 10.96.0.10
Default server: 10.96.0.10
Address: 10.96.0.10#53
> aliyun.com
Server:         10.96.0.10
Address:        10.96.0.10#53

Non-authoritative answer:
Name:   aliyun.com
Address: 140.205.135.3
Name:   aliyun.com
Address: 140.205.60.46
Name:   aliyun.com
Address: 106.11.248.144
Name:   aliyun.com
Address: 106.11.253.86
Name:   aliyun.com
Address: 106.11.172.51
Name:   aliyun.com
Address: 106.11.248.146
Name:   aliyun.com
Address: 106.11.253.83
Name:   aliyun.com
Address: 106.11.172.56
Name:   aliyun.com
Address: 106.11.172.9
Name:   aliyun.com
Address: 106.11.249.99

[root@iZuf60ytt884ww7f8td9m4Z ~]# ping aliyun.com
PING aliyun.com (140.205.135.3) 56(84) bytes of data.
64 bytes from 140.205.135.3 (140.205.135.3): icmp_seq=1 ttl=50 time=3.07 ms
64 bytes from 140.205.135.3 (140.205.135.3): icmp_seq=2 ttl=50 time=3.22 ms
^C
--- aliyun.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 3.078/3.153/3.229/0.094 ms
[root@iZuf60ytt884ww7f8td9m4Z ~]#

On any worker:
[root@iZuf63v0brg9kpz51w82pjZ ~]# nslookup 
> server 10.96.0.10
Default server: 10.96.0.10
Address: 10.96.0.10#53
> aliyun.com
;; connection timed out; no servers could be reached
> 

[root@iZuf63v0brg9kpz51w82pjZ ~]# ping aliyun.com
PING aliyun.com (140.205.135.3) 56(84) bytes of data.
64 bytes from 140.205.135.3 (140.205.135.3): icmp_seq=1 ttl=50 time=3.25 ms
64 bytes from 140.205.135.3 (140.205.135.3): icmp_seq=2 ttl=50 time=3.12 ms
64 bytes from 140.205.135.3 (140.205.135.3): icmp_seq=3 ttl=50 time=3.06 ms
^C
--- aliyun.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 3.067/3.149/3.256/0.091 ms

**Comment by JasperDiShu** [comment]
[root@iZuf60ytt884ww7f8td9m4Z ~]# kubectl get ippool -oyaml
apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"2558fa6d-e3ec-4e9c-bc3e-6237b9c0bce6","creationTimestamp":"2022-05-25T13:23:49Z"}'
    creationTimestamp: "2022-05-25T13:23:49Z"
    generation: 1
    managedFields:
    - apiVersion: crd.projectcalico.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:projectcalico.org/metadata: {}
        f:spec:
          .: {}
          f:allowedUses: {}
          f:blockSize: {}
          f:cidr: {}
          f:ipipMode: {}
          f:natOutgoing: {}
          f:nodeSelector: {}
          f:vxlanMode: {}
      manager: Go-http-client
      operation: Update
      time: "2022-05-25T13:23:49Z"
    name: default-ipv4-ippool
    resourceVersion: "1618"
    uid: cd0801c2-d4f4-414e-8b3a-e5f6a77f202b
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 100.64.0.0/10
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: CrossSubnet
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by Andrewcyh** [comment]
Have two solutions:
1. temporary solution：
- Replace crd/ippool vxlanMode: "CrossSubnet" with vxlanMode: "Always"
2. permanent solution:
operator: crd/installation
-  Replace bgp: "Enabled" with bgp: "Disabled"
manifest: daemonset/calico-node
-  Replace calico_backend: "bird" with calico_backend: "vxlan"
-  Comment out the line - -bird-ready and - -bird-live from the calico/node readiness/liveness check (otherwise disabling BIRD will cause the readiness/liveness check to fail on every node)

**Comment by fanux** [comment]
1. exec `echo "nameserver 8.8.8.8">  /etc/resolv.conf` on all nodes.
2. restart coredns
