### ISSUE TITLE
All plugin run twice

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1460]
#### What happened:

![image](https://user-images.githubusercontent.com/23137196/172058359-c4aef3d8-5ee0-438d-ab01-2006c9729ae3.png)

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
@VinceCui 
Kind remind. You could just paste the content directly here with quote next time, rather snip a picture here.

**Comment by kakaZhou719** [comment]
@VinceCui ,how can i reproduce this issue? if plugin specify in clusterfile , and also in the cloudimage, it will run twice. But we should have a deduplication operation here.

**Comment by VinceCui** [comment]
@Stevent-fei Follow this issue.
