### ISSUE TITLE
Can't Use "kubectl top nodes" command, Prompt  "error: Metrics API not available"  error

### ISSUE THREAD

**Issue by chirsxjh** [sealerio/sealer#1490]
kubectl top nodes

#### What happened:

```
[root@xjhtest ~]# kubectl top nodes
error: Metrics API not available
```

#### What you expected to happen: 

how to obtain cluster monitoring information, such as cpu, memory of each node。Still need to install third-party monitoring tools？

#### Environment: Centos 7.4

- sealer version (use `sealer version`): \{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
 [root@xjh-test ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): [root@xjh-test ~]# uname -a
Linux xjh-test 3.10.0-1160.53.1.el7.x86_64  SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by imdingtalk** [comment]
This needs to install monitoring components such as Prometheus according to your needs. Sealer does not include these, only provides the basic K8S environment

**Comment by allencloud** [comment]
@chirsxjh 

> This may need to install monitoring components such as Prometheus according to your needs. Sealer does not include these, only provides the basic K8S environment

Yes, like @imdingtalk mentioned, sealer is a tool, and the base image in a ClusterImage may contain a kubernetes. If the embedded kubernetes contains prometheus, then there is metric component. If does not, there is no monitoring components. 

In a word, it depends on kubernetes within the ClusterImage you used.

**Comment by chirsxjh** [comment]
thanks!
