### ISSUE TITLE
platform adapter

### ISSUE THREAD

**Issue by shaobo322** [sealerio/sealer#1491]
#### What happened:

![image](https://user-images.githubusercontent.com/37969177/172754234-a211d143-4617-49d4-a913-5303bad1bed2.png)

![image](https://user-images.githubusercontent.com/37969177/172754119-177280e0-62c6-46f1-ac22-a4180ca7ef40.png)

![image](https://user-images.githubusercontent.com/37969177/172754293-c89e7bb9-0ae0-4d50-be7d-214818c8222a.png)

#### What you expected to happen:
expected create a k8s cluster with multi master 
```bash
sudo sealer run kubernetes:v1.19.8 --masters 192.168.64.2,192.168.64.4 --nodes 192.168.64.5 --user ubuntu
```

#### Environment:

- sealer version (use `sealer version`):
sealer was build from latest code( main branch)
- Cloud provider or hardware configuration:
![image](https://user-images.githubusercontent.com/37969177/172755152-4d6f880b-4564-4386-85ec-f6b954f96087.png)
- OS (e.g: `cat /etc/os-release`):
```bash
ubuntu@vm01:/var/lib/sealer/data/my-cluster/rootfs/scripts$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@shaobo322 ，pls try to use root user to execute `sealer run` with version 0.8.5 . Clusterimage `kubernetes:v1.19.8` support arm64 architecture.

**Comment by allencloud** [comment]
> @shaobo322 ，pls try to use root user to execute `sealer run` with version 0.8.5 . Clusterimage `kubernetes:v1.19.8` support arm64 architecture.

@kakaZhou719 
No use. I ran with root user, and met the same problem. It seems to be the problem of docker installation and Ubuntu Distribution issues.

**Comment by allencloud** [comment]
It has been fixed in https://github.com/sealerio/sealer/pull/1508
