### ISSUE TITLE
Sealer fails when run on AliOS at the second time.

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1497]
#### What happened:

![image](https://user-images.githubusercontent.com/23137196/173040119-452a2431-797a-4a70-b1ee-f912d35fcb64.png)

There is no idempotent judgment here. The docker0 bridge device will be successfully added in the first run, but the bridge will not be cleaned up when the cluster is cleaned up, which will lead to the following error when installing again:

这里没有做幂等判断，第一次运行会成功添加docker0网桥设备，但是清理集群时不会清理该网桥，这就导致再次安装时，hui会出现如下错误：

![image](https://user-images.githubusercontent.com/23137196/173040589-5956e66b-0a2d-4993-85ca-5ece06b71ed4.png)

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by VinceCui** [comment]
@Stevent-fei fix this bug for sealer and ack-d.

**Comment by bxy4543** [comment]
https://github.com/sealerio/basefs/blob/2c7490bfe47563c27fc2ae6cddb0e4a114dcc8c3/context/docker/rootfs/scripts/docker.sh#L64 @Stevent-fei 
determine whether it exists when adding docker0 bridge, `ip link show docker0`

and remove the docker0 bridge in the clean script when it exists.
