### ISSUE TITLE
Make plugin's "on" support |

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1501]
## Issue Description

When i write a plugin, i can use "on" to specify where should it run.

Now, "on" support master/node, HOWEVER, when i want one plugin run on both master and node, i need to write two same plugin, and only "on" is different.

So, i think maybe "on" can support "|" operation, just like "action".

For example, when i specify "master|node", that plugin will run on both master and node.

Type: *feature request*

**Comment by bxy4543** [comment]
https://github.com/sealerio/sealer/blob/main/pkg/plugin/utils.go#L37

**Comment by YTGhost** [comment]
I'm going to get this done.
