### ISSUE TITLE
runtime module improve

### ISSUE THREAD

**Issue by starComingup** [sealerio/sealer#1504]
## Issue Description

Type: *code ugly*

### Describe what feature you want
When i want to contribute the #1404 , I found the runtime module is hard to adapt the k0s、k3s、microk8s scenes to implements the method such as kubeadm runtime interface. 

On another hand, as a new developer. It takes me a lot time to understand every file in Runtime module. As for k8s user, we all know kubeadm has every step task to lead install. So if we got a clear file name or pipeline Interface name, which would make developers easier to read the code.

In my point of view，I would like the module like package(apply) with processor.

follow is my suggest for runtime module.
```bash
runtime
├── kubeadm
│   ├── create_cluster.go
│   ├── add_nodes.go
│   ├── renew_certs.go
│   ├── upgrade_cluster.go
│   ├── registry.go
│   └── ...
└── k0sctl
    └── create_cluster.go

```

**Comment by starComingup** [comment]
@allencloud Thanks for reply.
I will design a architecture with Runtime module and basefs interface in no soon. And I want to know if this community have a meeting calendar like others, this would make more convenience for us to discuss all about Sealer.

**Comment by allencloud** [comment]
> if this community have a meeting calendar like others,

@starComingup please refer to https://github.com/sealerio/community/blob/main/README.md . Actually we have arranged maintainer meeting already. While for the community meeting, it has already inactive, and we should restart that later. I think we need some community participants who volunteer to host this meeting.

**Comment by starComingup** [comment]
@allencloud fine，It is my great honor that invited by your maintainer discussion.
here is my design of runtime module link https://www.yuque.com/docs/share/83c8e538-bce8-434e-9550-c5f4895ba412?# 《Runtime Design》
and I need some suggestion of maintainers to improve the design, because I may have some improper though in this draft as a green hand.

**Comment by justadogistaken** [comment]
@starComingup LOL, you are being so modest. Thanks for you great job.
@allencloud I think we can expand the meeting scope from "maintainer" to "member"/"community" in several days, or to "member" first.
