### ISSUE TITLE
The func check_registry in init-registry.sh script reports error

### ISSUE THREAD

**Issue by jinsongo** [sealerio/sealer#1507]
#### What happened:
The command `sealer run` reports the following error:
```
+ check_registry
+ n=1
init-registry.sh: 44: cannot open =: No such file
+ n 3
init-registry.sh: 44: n: not found
```
The function startRegistry() could have the same problem, please check.
https://github.com/sealerio/basefs/blob/main/context/containerd/rootfs/scripts/init-registry.sh

#### What you expected to happen:
init-registry.sh script should run successfully.

#### How to reproduce it (as minimally and precisely as possible):
```sealer run registry.cn-qingdao.aliyuncs.com/sealer-apps/openebs-localpv:3.2.0 --masters xxxxxx --nodes xxxxxx --passwd xxxxxx```
It's okay to reproduce with other sealer images.

#### Environment:
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
# uname -a
Linux ubuvm-instana.fyre.ibm.com 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu
```

```
# sealer version
{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}
```

**Comment by jinsongo** [comment]
@bxy4543 @kakaZhou719 @allencloud  It seems the cluster still can be deployed successfully. Could you please explain what problem could be caused by the init-registry error? Thanks a lot.

**Comment by bxy4543** [comment]
same issue: https://github.com/sealerio/sealer/issues/1454, 
next version will fix this problem

**Comment by allencloud** [comment]
I reproduced this issue.

**Comment by allencloud** [comment]
> same issue: #1454, next version will fix this problem

@bxy4543 No, they are different issues. Not the same.

**Comment by allencloud** [comment]
@jinsongo @bxy4543 
It is because the tool `sh` on Ubuntu 20.04 LTS cannot be compatible with `#!/bin/bash`. In https://github.com/sealerio/sealer/blob/cf9bdb1667d6d519aa0af63037999d73646dcbb4/pkg/runtime/registry.go#L73 , there is `sh init-registry.sh`. And it would report the above error.

I did a test for this on ubuntu 20.04 LTS:

1. touch and edit a test.sh
```
root@sealer:~# cat test.sh
#!/bin/bash

check_registry() {
    n=1
    while (( n <= 3 ))
    do
	echo "this is NO $n"
       (( n++ ))
        sleep 3
    done
}

check_registry
```

2. run it wish /bin/bash, and it is OK
```
root@sealer:~# /bin/bash test.sh
this is NO 1
this is NO 2
this is NO 3

```

3. run it with `sh`, then it fails:
```
root@sealer:~# sh test.sh
test.sh: 5: cannot open =: No such file
test.sh: 5: n: not found
root@sealer:~# /bin/bash test.sh
```

**Comment by jinsongo** [comment]
It's better to use the compatible usage about the variable `n` for bash/dash.

**Comment by allencloud** [comment]
> https://github.com/sealerio/basefs/blob/main/context/containerd/rootfs/scripts/init-registry.sh

@jinsongo In the future, sealer would try to avoid shell composing as possible. Instead, it would be quite secure that we use `POSIX` directly to improve compatibility.
