### ISSUE TITLE
Need v1.24.0 kubernetes images with docker runtime to run

### ISSUE THREAD

**Issue by zhabinecho** [sealerio/sealer#1511]
## Issue Description

Need v1.24.0 kubernetes images with docker runtime to run

**Comment by bxy4543** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd/
If you still need to use docker as CRI, you can try cri-docker, just switching from the built in dockershim to the external one.
