### ISSUE TITLE
Support sealer alpha command to incubate some alpha features

### ISSUE THREAD

**Issue by allencloud** [sealerio/sealer#1522]
Hi, All,

sealer aims to solve distributed application packaging/distributing/running issues. Currently, it has already supported many command, like, run, apply, build and so on.

While, when receiving more and more feature requests, sealer community found that sealer could accept some of them, but the feature may need long-term design, experiment and improvement. In a word, some features may still be early stage.

For these feature request, sealer community takes quite open attitude, and wishes to open another policy to support this--`sealer alpha` command. For example, sealer maintainer discussed the `take-over` command should be included in `sealer alpha`, since it is not so mature, but still wish more end-users could experience and input more advices.

Here are some features that we plan to include in alpha command.

- [ ] take-over command
- [ ] upgrade command
- [ ] no-underlying-base-support

Welcome all participants to input more ideas about alpha command

**Comment by kakaZhou719** [comment]
those sealer cmd could we move it to alpha command to incubate?

1. `sealer prune`
2. `sealer search`
3. `sealer debug`
4. `sealer exec`
5. `sealer cert`

**Comment by allencloud** [comment]
@kakaZhou719 I think we can do that except `sealer search`.
