### ISSUE TITLE
failed to clone sealer repo

### ISSUE THREAD

**Issue by shy-Xu** [sealerio/sealer#1530]
#### What happened:
When I want clone sealer repository to my computer, a fatal happend.
![image](https://user-images.githubusercontent.com/53456509/174431180-d50d6712-a2e2-4be8-90dc-7f0743329568.png)

It seems that the problem is .github/weekly-digest.yml, and my computer's os is windows.

#### Environment:

- sealer version (use `sealer version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Great finding. I found that I named the file with `weekly-digest.yml ` rather than `weekly-digest.yml`. See? With a white space suffix in the former one. @shy-Xu 

I have tried to update the file name in https://github.com/sealerio/sealer/pull/1531 .
