### ISSUE TITLE
放宽overlay挂载限制

### ISSUE THREAD

**Issue by ningpengtao-coder** [sealerio/sealer#1547]
问题描述
目前sealer build image时会检测是否支持overlay文件系统。当前默认通过modprobe overlay去检测，我发现在容器环境和wsl2都会导致最终保存失败(能够保存，但是拉取的镜像丢失，算作保存失败)。

解决方案：
去除overlay2.go中modprobe检测，仅使用/proc/filesystems去检测。并希望能够在不支持overlay的情况下，通过日志在控制台上显示。
https://github.com/sealerio/sealer/blob/cf9bdb1667d6d519aa0af63037999d73646dcbb4/utils/mount/overlay2.go#L49

**Comment by YTGhost** [comment]
I'm going to get this done.
