### ISSUE TITLE
[help] want to diff the k8s、k0s、k3s

### ISSUE THREAD

**Issue by starComingup** [sealerio/sealer#1549]
### What happen?

want to help! 
I can't diff the k8s、k0s、k3s which the user would like to install or manager.
If there is a best method for me to diff the k8s、k0s、k3s？
```bash
/var/lib/sealer/data/my-cluster/rootfs# cat Metadata
{
  "version": "v1.19.8",
  "arch": "amd64"
}
```

### What you expected to happen?

I seem to look a method to use a Metadata field or something else to diff k8s、k3s、k0s , but It seems there is no existing a func for me to use.

Another Bug is that I install a v1.24.1 Kubernetes, but the Metadata show the field Version:`v1.19.8`

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
@starComingup I think adding a filed `clusterRuntime` is fine for this feature.

**Comment by starComingup** [comment]
@justadogistaken @allencloud thanks for reply, that is a good idea, i will try it!
