### ISSUE TITLE
different log formats

### ISSUE THREAD

**Issue by sfeng1996** [sealerio/sealer#1584]
### What happen?

The console prints out different log formats

![image](https://user-images.githubusercontent.com/52435865/179131350-00b0fb68-3220-4946-8544-2f2b81c7b29a.png)

### What is the version of Sealer you using?

{"gitVersion":"v0.8.6","gitCommit":"884513e","buildDate":"2022-07-12 02:58:54","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### What is the Kernel version?

Linux master-172-31-97-104 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by allencloud** [comment]
@sfeng1996 
Yeah, the blue ones are sealer's log and its format is from [logrus](https://github.com/sirupsen/logrus). Currently the default log format is logrus. The the logs with `preflight` prefix are from kubeadm which is called by sealer.

**Comment by sfeng1996** [comment]
> @sfeng1996 Yeah, the blue ones are sealer's log and its format is from [logrus](https://github.com/sirupsen/logrus). Currently the default log format is logrus. The the logs with `preflight` prefix are from kubeadm which is called by sealer.

I may not have described it clearly. I mean there are two kinds of blue on the console, one of which is like the previous sealer logger format
