### ISSUE TITLE
集群间service访问不通

### ISSUE THREAD

**Issue by djwangyi** [sealerio/sealer#1590]
### What happen?

初始化完sealer，通过helm安装完mysql，发现mysql只能在pod当前的node节点可以访问，但是跨节点不能访问。发现在其他节点 telnet对应mysql 3306端口不通。将安全组全部放开也无用。

### Relevant log output?

```Shell
[root@VM-0-47-centos ~]# kubectl get  svc -A |grep "mysql"
mysql-system       mysql                             ClusterIP   10.96.0.183   <none>        3306/TCP                 2m52s
mysql-system       mysql-headless                    ClusterIP   None          <none>        3306/TCP                 2m52s
mysql-system       mysql-metrics                     ClusterIP   10.96.3.91    <none>        9104/TCP                 2m52s

[root@VM-0-47-centos ~]# kubectl get pod -A -owide |grep "mysql"
mysql-system         mysql-0                                    2/2     Running   0          9m36s   100.73.157.194    vm-0-9-centos    <none>           <none>


[root@VM-0-47-centos ~]# ping 10.96.0.183
PING 10.96.0.183 (10.96.0.183) 56(84) bytes of data.
64 bytes from 10.96.0.183: icmp_seq=1 ttl=64 time=0.047 ms
64 bytes from 10.96.0.183: icmp_seq=2 ttl=64 time=0.028 ms

[root@VM-0-47-centos ~]# telnet 10.96.0.183 3306
Trying 10.96.0.183...

[root@VM-0-9-centos ~]# telnet 10.96.0.183 3306
Trying 10.96.0.183...
Connected to 10.96.0.183.
Escape character is '^]'.
J
```

### What you expected to happen?

理论上 serivce的 ClusterIP加端口在集群内任何节点都可以访问。

### How to reproduce it (as minimally and precisely as possible)?

```YAML
1.sealer run kubernetes:v1.19.8  -m 172.16.0.47,172.16.0.46,172.16.0.9

2. kubectl taint nodes --all node-role.kubernetes.io/master-

3. kubectl apply -f local-path-storage.yaml

3. helm repo add bitnami https://charts.bitnami.com/bitnami

4. helm fetch bitnami/mysql

5. tar -zxvf mysql-9.2.0.tgz

6. helm install  mysql -f mysql/mysql-values.yaml --create-namespace --namespace mysql-system mysql/
```

### Anything else we need to know?

mysql-values.yaml 

global:
  storageClass: "local-path"
auth:
  username: nacos
  password: nacos
  database: nacos_config
  rootPassword: `123456`
architecture: standalone
metrics:
  enabled: true

---
local-path-storage.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "persistentvolumeclaims", "configmaps" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints", "persistentvolumes", "pods" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.22
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/local-path-provisioner"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent

### What is the version of Sealer you using?

{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="TencentOS Server" VERSION="2.4" ID="tencentos" ID_LIKE="rhel fedora centos tlinux" VERSION_ID="2.4" PRETTY_NAME="TencentOS Server 2.4" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:tencentos:tencentos:2" HOME_URL="https://cloud.tencent.com/product/ts"

### What is the Kernel version?

Linux VM-0-47-centos 3.10.107-1-tlinux2_kvm_guest-0056 #1 SMP Wed Dec 29 14:35:09 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
Is your kube-proxy from "VM-0-47-centos" running well?

**Comment by djwangyi** [comment]
> 您来自“VM-0-47-centos”的 kube-proxy 运行良好吗？
 
[root@VM-0-47-centos ~]# kubectl get pod -A -owide|grep "proxy"
kube-system          kube-proxy-hqhpt                           1/1     Running   0          53m   172.16.0.47       vm-0-47-centos   <none>           <none>
kube-system          kube-proxy-mg6s7                           1/1     Running   0          53m   172.16.0.46       vm-0-46-centos   <none>           <none>
kube-system          kube-proxy-t2npt                           1/1     Running   0          52m   172.16.0.9        vm-0-9-centos    <none>           <none>


[root@VM-0-47-centos ~]# kubectl logs -n kube-system          kube-proxy-hqhpt 
I0716 06:10:19.824915       1 node.go:136] Successfully retrieved node IP: 172.16.0.47
I0716 06:10:19.824964       1 server_others.go:142] kube-proxy node IP is an IPv4 address (172.16.0.47), assume IPv4 operation
I0716 06:10:19.842031       1 server_others.go:258] Using ipvs Proxier.
E0716 06:10:19.842211       1 proxier.go:381] can't set sysctl net/ipv4/vs/conn_reuse_mode, kernel version must be at least 4.1
W0716 06:10:19.842297       1 proxier.go:434] IPVS scheduler not specified, use rr by default
I0716 06:10:19.842471       1 server.go:650] Version: v1.19.8
I0716 06:10:19.842814       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0716 06:10:19.843096       1 config.go:224] Starting endpoint slice config controller
I0716 06:10:19.843111       1 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
I0716 06:10:19.843150       1 config.go:315] Starting service config controller
I0716 06:10:19.843156       1 shared_informer.go:240] Waiting for caches to sync for service config
I0716 06:10:19.943242       1 shared_informer.go:247] Caches are synced for service config 
I0716 06:10:19.943243       1 shared_informer.go:247] Caches are synced for endpoint slice config 

看pod是正常的，看对应日志，启动没问题，只有一行日志 can't set sysctl net/ipv4/vs/conn_reuse_mode, kernel version must be at least 4.1，像是版本的问题。

**Comment by justadogistaken** [comment]
Can you ping or access(telnet) the pod directly in "VM-0-47-centos"?

**Comment by djwangyi** [comment]
> Can you ping or access(telnet) the pod directly in "VM-0-47-centos"?

[root@VM-0-47-centos ~]# kubectl get pod -A -owide|grep "mysql"
mysql-system         mysql-0                                    2/2     Running   0          112m   100.73.157.194    vm-0-9-centos    <none>           <none>

[root@VM-0-47-centos ~]# ping 100.73.157.194
PING 100.73.157.194 (100.73.157.194) 56(84) bytes of data.

[root@VM-0-47-centos ~]# kubectl get pod -A -owide|grep "47"
calico-apiserver     calico-apiserver-787957dccb-jpjcf          1/1     Running   0          115m   100.121.255.130   vm-0-47-centos   <none>           <none>

[root@VM-0-47-centos ~]# ping 100.121.255.130
PING 100.121.255.130 (100.121.255.130) 56(84) bytes of data.
64 bytes from 100.121.255.130: icmp_seq=1 ttl=64 time=0.042 ms
64 bytes from 100.121.255.130: icmp_seq=2 ttl=64 time=0.039 ms

ping 跨node的pod 是不通的， ping 自己node的pod 是没问题的。

**Comment by justadogistaken** [comment]
@djwangyi I guess the problem is caused by "cni". I guess we don't have cni installed by default.

**Comment by djwangyi** [comment]
> @djwangyi我猜这个问题是由“cni”引起的。我猜我们默认没有安装 cni。

我看默认装的是Calico。

NAMESPACE            NAME                                       READY   STATUS    RESTARTS   AGE   IP                NODE             NOMINATED NODE   READINESS GATES
calico-apiserver     calico-apiserver-787957dccb-jpjcf          1/1     Running   0          44h   100.121.255.130   vm-0-47-centos   <none>           <none>
calico-apiserver     calico-apiserver-787957dccb-wvznw          1/1     Running   0          44h   100.117.224.3     vm-0-46-centos   <none>           <none>
calico-system        calico-kube-controllers-69dfd59986-dd6k5   1/1     Running   0          44h   100.117.224.1     vm-0-46-centos   <none>           <none>
calico-system        calico-node-kr2t6                          1/1     Running   0          44h   172.16.0.9        vm-0-9-centos    <none>           <none>
calico-system        calico-node-s2jnh                          1/1     Running   0          44h   172.16.0.47       vm-0-47-centos   <none>           <none>
calico-system        calico-node-tvbct                          1/1     Running   0          44h   172.16.0.46       vm-0-46-centos   <none>           <none>
calico-system        calico-typha-55d54ff446-l55bj              1/1     Running   0          44h   172.16.0.47       vm-0-47-centos   <none>           <none>
calico-system        calico-typha-55d54ff446-zv2gb              1/1     Running   0          44h   172.16.0.46       vm-0-46-centos   <none>           <none>

我看Calico-client的status信息，也没有看出问题所在：
[root@VM-0-9-centos /]# calico-node -show-status

bird v4 status
+-------+-------------------+------------+---------------------+---------------------+---------------------+
| READY |      VERSION      |  ROUTEID   |     SERVERTIME      |      LASTBOOT       |    LASTRECONFIG     |
+-------+-------------------+------------+---------------------+---------------------+---------------------+
| true  | v0.3.3+birdv1.6.8 | 172.16.0.9 | 2022-07-18 02:33:16 | 2022-07-16 06:11:41 | 2022-07-16 06:11:41 |
+-------+-------------------+------------+---------------------+---------------------+---------------------+

bird v4 BGP peers
+--------------+-----------+-------+------------+-------------+
| PEER ADDRESS | PEER TYPE | STATE |   SINCE    |  BGPSTATE   |
+--------------+-----------+-------+------------+-------------+
| 172.16.0.46  | Mesh      | up    | 2022-07-16 | Established |
| 172.16.0.47  | Mesh      | up    | 2022-07-16 | Established |
+--------------+-----------+-------+------------+-------------+

bird v4 routes
+--------------------+-------------+-----------------+------------------+---------+
|    DESTINATION     |   GATEWAY   |      IFACE      |   LEARNEDFROM    | PRIMARY |
+--------------------+-------------+-----------------+------------------+---------+
| 0.0.0.0/0          | 172.16.0.1  | eth0            | kernel1          | *       |
| 100.117.224.0/26   | 172.16.0.46 | eth0            | Mesh_172_16_0_46 | *       |
| 100.117.224.0/26   | 172.16.0.46 | eth0            | Mesh_172_16_0_46 |         |
| 100.117.224.0/26   | 172.16.0.46 | eth0            | Mesh_172_16_0_47 |         |
| 100.117.224.0/26   | 172.16.0.46 | eth0            | kernel1          |         |
| 169.254.0.0/16     | N/A         | eth0            | kernel1          | *       |
| 100.121.255.128/26 | 172.16.0.47 | eth0            | Mesh_172_16_0_46 | *       |
| 100.121.255.128/26 | 172.16.0.47 | eth0            | Mesh_172_16_0_47 |         |
| 100.121.255.128/26 | 172.16.0.47 | eth0            | Mesh_172_16_0_47 |         |
| 100.121.255.128/26 | 172.16.0.47 | eth0            | kernel1          |         |
| 100.73.157.194/32  | N/A         | cali7797b342377 | kernel1          | *       |
| 100.73.157.192/26  | N/A         | blackhole       | static1          | *       |
| 100.73.157.192/26  | N/A         | blackhole       | kernel1          |         |
| 100.73.157.192/32  | N/A         | vxlan.calico    | direct1          | *       |
| 172.17.0.0/16      | N/A         | docker0         | direct1          | *       |
| 172.16.0.0/20      | N/A         | eth0            | direct1          | *       |
+--------------------+-------------+-----------------+------------------+---------+



bird v6 status
+-------+-------------------+------------+---------------------+---------------------+---------------------+
| READY |      VERSION      |  ROUTEID   |     SERVERTIME      |      LASTBOOT       |    LASTRECONFIG     |
+-------+-------------------+------------+---------------------+---------------------+---------------------+
| true  | v0.3.3+birdv1.6.8 | 172.16.0.9 | 2022-07-18 02:33:16 | 2022-07-16 06:11:41 | 2022-07-16 06:11:41 |
+-------+-------------------+------------+---------------------+---------------------+---------------------+

bird v6 BGP peers
+--------------+-----------+-------+-------+----------+
| PEER ADDRESS | PEER TYPE | STATE | SINCE | BGPSTATE |
+--------------+-----------+-------+-------+----------+
+--------------+-----------+-------+-------+----------+

bird v6 routes
+-------------------+---------+-------------+-------------+---------+
|    DESTINATION    | GATEWAY |    IFACE    | LEARNEDFROM | PRIMARY |
+-------------------+---------+-------------+-------------+---------+
| ::/96             | N/A     | unreachable | kernel1     | *       |
| 2002:a00::/24     | N/A     | unreachable | kernel1     | *       |
| 3ffe:ffff::/32    | N/A     | unreachable | kernel1     | *       |
| 2002:7f00::/24    | N/A     | unreachable | kernel1     | *       |
| 2002:a9fe::/32    | N/A     | unreachable | kernel1     | *       |
| 2002:ac10::/28    | N/A     | unreachable | kernel1     | *       |
| 2002:e000::/19    | N/A     | unreachable | kernel1     | *       |
| 2002:c0a8::/32    | N/A     | unreachable | kernel1     | *       |
| ::ffff:0.0.0.0/96 | N/A     | unreachable | kernel1     | *       |
+-------------------+---------+-------------+-------------+---------+

**Comment by justadogistaken** [comment]
@djwangyi How about searching for solutions from "calico" or "k8s" community?

**Comment by djwangyi** [comment]
> @djwangyi从“calico”或“k8s”社区搜索解决方案怎么样？

问题解决了，我不再用默认的calico，改为https://github.com/sealerio/applications/tree/main/flannel，将calico替换为flannel，重新打了镜像部署的，网络通信正常了。
