### ISSUE TITLE
普通用户是否可以使用sealer一键部署？

### ISSUE THREAD

**Issue by Phoebus888** [sealerio/sealer#1591]
有的客户那边不想给root用户,给了一个普通用户用于安装k8s   这边是否可以使用普通用户呢

**Comment by tanxiaoning007** [comment]
至少需要一个拥有sudo权限的用户

**Comment by allencloud** [comment]
> 有的客户那边不想给root用户,给了一个普通用户用于安装k8s 这边是否可以使用普通用户呢

@Phoebus888 sealer does not support installing and running by a normal user which has no sudo permission. 

Currently, sealer still does not support a normal user with sudo permission. While in the future after some refactoring of sealer, we will definitely support a normal user with sudo permission.
