### ISSUE TITLE
sealer push failed, Error: failed to push layers of xxx, err: received unexpected HTTP status: 200 OK

### ISSUE THREAD

**Issue by windydayc** [sealerio/sealer#1597]
### What happen?

sealer push failed, Error: failed to push layers of xxx, err: received unexpected HTTP status: 200 OK

### Relevant log output?

```Shell
[root@host8c tmp]# sealer login docker.io -u zengfeng666 -p xxx
2022-07-20 18:34:28 [INFO] [default_image.go:236] zengfeng666 login docker.io success
[root@host8c tmp]# 
[root@host8c tmp]# 
[root@host8c tmp]# sealer tag kubernetes:v1.19.8-alpine docker.io/zengfeng666/kubernetes:v1.19.8-alpine
[root@host8c tmp]# sealer push docker.io/zengfeng666/kubernetes:v1.19.8-alpine
Start to Push Image docker.io/zengfeng666/kubernetes:v1.19.8-alpine
6af04e85d342: push failed 
ebd0f721b47d: push failed 
1066d30573cf: push failed 
869b45ef4055: push failed 
Error: failed to push layers of docker.io/zengfeng666/kubernetes:v1.19.8-alpine, err: received unexpected HTTP status: 200 OK
Usage:
  sealer push [flags]

Examples:
sealer push registry.cn-qingdao.aliyuncs.com/sealer-io/my-kubernetes-cluster-with-dashboard:latest

Flags:
  -h, --help   help for push

Global Flags:
      --config string   config file (default is $HOME/.sealer.json)
  -d, --debug           turn on debug mode
      --hide-path       hide the log path
      --hide-time       hide the log time

failed to push layers of docker.io/zengfeng666/kubernetes:v1.19.8-alpine, err: received unexpected HTTP status: 200 OK
```

### What you expected to happen?

push the image to dockerhub successfully.

### What is the version of Sealer you using?

{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

centos7

### What is the Kernel version?

Linux host8c 3.10.0-693.el7.x86_64

**Comment by justadogistaken** [comment]
@windydayc change domain to "registry-1.docker.io" may help solve this problem. I found sealer has no logic for transforming domain automatically.

**Comment by windydayc** [comment]
> @windydayc change domain to "registry-1.docker.io" may help solve this problem. I found sealer has no logic for transforming domain automatically.

Thanks.
