### ISSUE TITLE
Failed to create cluster

### ISSUE THREAD

**Issue by xrwang8** [sealerio/sealer#1610]
### What happen?

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/68765051/181473779-3ac47735-4bf9-4c1d-b01c-7637f7554059.png">

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by xiaozitwo** [comment]
Are you use sealer create cluster on WSL2？

**Comment by allencloud** [comment]
@xrwang8 Actually the error log is still incomplete. Could you paste all the logs?
