### ISSUE TITLE
Duplicate sending certificate when run sealer join

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1613]
### What happen?

when I was learning the runtime code, I found a weird problem:

`sealer join`:  Generate duplicate ca certificates. 

The runtime code process is as follows:
1.  the first step is to send all master0 certificates to new joined master including CA certificates, api server cert and so on . 
2. the second step is to regenerate all certificates including CA certificates on the new joined master.  overwrite ?

### What you expected to happen?

A cluster has only one CA certificate, and other components can generate their own cert and key based on this certificate.

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by jsparter** [comment]
I will check it out first.

**Comment by justadogistaken** [comment]
@jsparter Maybe all masters share the ca already. I mean the ca has been sent to every master before join it probably .
