### ISSUE TITLE
Useless action

### ISSUE THREAD

**Issue by justadogistaken** [sealerio/sealer#1630]
### What happen?

I commend `/test apply`
And two actions executed.
I think this could be avoided.
![Uploading Screen Shot 2022-08-11 at 23.36.03.png…]()

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by allencloud** [comment]
@justadogistaken your picture has not been uploaded. Please take another look.
