### ISSUE TITLE
failed to run sealer clusterimage with containerd 

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1638]
### What happen?

I found several problems when trying to run containerd's cluster image :

1. wrong kubeadm config when join node, seems this using default config when merging kubeadm.yaml

`criSocket: /var/run/dockershim.sock`

2. wrong containerd sandbox domain from dump-config.toml: 

`k8s.gcr.io/pause:3.7` , i think it should be the default registry domain `sea.hub:5000` Or overwrite it in the next install process. Otherwise,CRI  will failed to pull images.

3. wrong kubelet access credential file path:

code from registry,go:  `cp /root/.docker/config.json /var/lib/kubelet`

if `/var/lib/kubelet` is not exist, `/var/lib/kubelet`  will be a file with config.json as its content. that will cause 401 .

### Anything else we need to know?

`kubernetes:v1.24.0`

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
@kakaZhou719 Do you have any idea that who build this image?

**Comment by kakaZhou719** [comment]
> @kakaZhou719 Do you have any idea that who build this image?

I’m not sure about this.
@VinceCui FYI, kebeadm refactoring .

**Comment by myselfghost** [comment]
> ### What happen?
> I found several problems when trying to run containerd's cluster image :
> 
> 1. wrong kubeadm config when join node, seems this using default config when merging kubeadm.yaml
> 
> `criSocket: /var/run/dockershim.sock`
> 
> 2. wrong containerd sandbox domain from dump-config.toml:
> 
> `k8s.gcr.io/pause:3.7` , i think it should be the default registry domain `sea.hub:5000` Or overwrite it in the next install process. Otherwise,CRI will failed to pull images.
> 
> 3. wrong kubelet access credential file path:
> 
> code from registry,go: `cp /root/.docker/config.json /var/lib/kubelet`
> 
> if `/var/lib/kubelet` is not exist, `/var/lib/kubelet` will be a file with config.json as its content. that will cause 401 .
> 
> ### Relevant log output?
> _No response_
> 
> ### What you expected to happen?
> _No response_
> 
> ### How to reproduce it (as minimally and precisely as possible)?
> _No response_
> 
> ### Anything else we need to know?
> `kubernetes:v1.24.0`
> 
> ### What is the version of Sealer you using?
> _No response_
> 
> ### What is your OS environment?
> _No response_
> 
> ### What is the Kernel version?
> _No response_
> 
> ### Other environment you want to tell us?
> * Cloud provider or hardware configuration:
> * Install tools:
> * Others:

Yes, it will cause the installation process to fail

**Comment by kakaZhou719** [comment]
@myselfghost ，Don't worry, we will fix this in the next version. And there will be a surprising user experience。😊

**Comment by myselfghost** [comment]
> @myselfghost ，Don't worry, we will fix this in the next version. And there will be a surprising user experience。😊

@kakaZhou719   Please pay attention to this issue
https://github.com/sealerio/sealer/issues/1646
