### ISSUE TITLE
阿里云用sealer安装k8s1.19.8无法用service的nodeport访问

### ISSUE THREAD

**Issue by z5614036** [sealerio/sealer#1640]
### What happen?

<img width="802" alt="image" src="https://user-images.githubusercontent.com/24545834/184613863-abac135e-a355-4d52-b768-e93bb2b33233.png">

### Relevant log output?

```Shell
sealos安装的  nodeport 访问不了
```

### What you expected to happen?

9000: error forwarding port 9000 to pod 7d62c957b8ea311d150ecb423ec519420b13ff1e84e98e79a3e4bbfac33bbeab, uid : unable to do port forwarding: socat not found

### How to reproduce it (as minimally and precisely as possible)?

```YAML
socat not found  宿主机没有 socat，安装了就可以运行了，  sealos能帮忙解决这个吗？ 阿里云ecs
```

### What is your OS environment?

centos7.6阿里云ecs

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by z5614036** [comment]
使用pod-forward方式缺少socat not found

**Comment by z5614036** [comment]
阿里云ecs使用后service的nodeport访问不通

**Comment by justadogistaken** [comment]
这个是用sealos部署的环境吗？可以到sealos社区提issue咨询。

**Comment by allencloud** [comment]
Closing this, if you run into any sealer issue, please do not hesitate to seek help from sealer community. @z5614036
