### ISSUE TITLE
Feature: sealer logout.

### ISSUE THREAD

**Issue by justadogistaken** [sealerio/sealer#1647]
## Issue Description

Currently, we can do `sealer login docker.io -u xxx -p xxx` to access private repository.
But there is no logout function.
This is not an urgent feature, but maybe it could be used.

### Describe what feature you want

Sealer logout to remove the auth info.
1. sealer logout docker.io
2. sealer pull docker.io/[private-repo]/xxxx:xxxx failed.

**Comment by justadogistaken** [comment]
@jsparter

**Comment by jsparter** [comment]
I'm going to get this done.
