### ISSUE TITLE
If install K8s locally, sealer should not use ssh

### ISSUE THREAD

**Issue by windydayc** [sealerio/sealer#1691]
## Issue Description

Type: *feature request*

### Describe what feature you want
If install K8s locally, sealer should not use ssh. Because if the machine has a public IP address, ssh will fail.

**Comment by rambohe-ch** [comment]
@justadogistaken I think if end users install K8s locally, it's not need for them to input password. In another words, if no password is input for `sealer run` command, we can consider that a standalone kubernetes cluster will be installed locally.

and i will take this issue and post a pull request.
/assign @rambohe-ch

**Comment by Stevent-fei** [comment]
> @justadogistaken I think if end users install K8s locally, it's not need for them to input password. In another words, if no password is input for `sealer run` command, we can consider that a standalone kubernetes cluster will be installed locally.
> 
> and i will take this issue and post a pull request. /assign @rambohe-ch

This problem has been solved in sealer0.8.6 version.

**Comment by rambohe-ch** [comment]
> > @justadogistaken I think if end users install K8s locally, it's not need for them to input password. In another words, if no password is input for `sealer run` command, we can consider that a standalone kubernetes cluster will be installed locally.
> > and i will take this issue and post a pull request. /assign @rambohe-ch
> 
> This problem has been solved in sealer0.8.6 version.

@Stevent-fei Thank you for your reply. @windydayc maybe we can try version v0.8.6 of sealer.

**Comment by windydayc** [comment]
> > > @justadogistaken I think if end users install K8s locally, it's not need for them to input password. In another words, if no password is input for `sealer run` command, we can consider that a standalone kubernetes cluster will be installed locally.
> > > and i will take this issue and post a pull request. /assign @rambohe-ch
> > 
> > 
> > This problem has been solved in sealer0.8.6 version.
> 
> @Stevent-fei Thank you for your reply. @windydayc maybe we can try version v0.8.6 of sealer.

I will try `sealer run`. And I hope that `sealer apply` can also support it in the future.
