### ISSUE TITLE
sealer run cluster failed

### ISSUE THREAD

**Issue by tgfree7** [sealerio/sealer#1720]
### What happen?

Sealer run a cluster failed

### Relevant log output?

```Shell
2022-09-19 04:04:50 [ERROR] [root.go:77] sealer-latest: read .: is a directory
```

### What you expected to happen?

Run a cluster.

### How to reproduce it (as minimally and precisely as possible)?

```YAML
make build and run cmd:

sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8.test
```

### Anything else we need to know?

On branch main,  this may caused by func `NewClusterFile(path string)`, path is empty.

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
This had been discussed in #1702.
Close it.
