### ISSUE TITLE
sealer run kubernetesv1.24.6 join node error

### ISSUE THREAD

**Issue by clcc2019** [sealerio/sealer#1733]
### What happen?

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/46099295/191909083-22c5eeb9-ffb0-4bd6-b96f-51fdf5f092d7.png">

why docker

init.sh
```bash
#!/bin/bash

set -e
set -x

#STORAGE=${1:-/var/lib/docker} compatible docker
REGISTRY_DOMAIN=${2-sea.hub}
REGISTRY_PORT=${3-5000}

chmod -R 755 ../bin/*
chmod 644 ../bin
cp ../bin/* /usr/bin

# Install containerd
chmod a+x containerd.sh
bash containerd.sh "$REGISTRY_DOMAIN" "$REGISTRY_PORT"
iptables -F
#vim /etc/sysctl.conf
cat <<EOF > /etc/sysctl.conf
vm.swappiness = 0
vm.dirty_bytes=33554432
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
kernel.sysrq = 1
fs.file-max = 1000000
fs.inotify.max_user_instances = 8192
fs.inotify.max_user_watches=1048576
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.tcp_max_syn_backlog = 16384
net.ipv4.tcp_max_tw_buckets = 6000
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.route.gc_timeout = 100
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_keepalive_probes = 10
net.ipv4.tcp_synack_retries = 1
net.core.somaxconn = 32768
net.core.netdev_max_backlog = 32768
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_max_orphans = 32768
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
echo fs.inotify.max_user_watches=1048576 | tee /etc/sysctl.d/40-max-user-watches.conf && sysctl --system
sysctl -p

# Modify kubelet conf
mkdir -p /etc/systemd/system/kubelet.service.d

if grep "SystemdCgroup = true" /etc/containerd/config.toml &>/dev/null; then
  driver=systemd
else
  driver=cgroupfs
fi

cat >/etc/systemd/system/kubelet.service.d/containerd.conf <<eof
[Service]
Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --cgroup-driver=${driver} --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock --image-service-endpoint=unix:///run/containerd/containerd.sock"
eof
if [ $(systemctl status containerd > /dev/null 2>&1; echo $?) != 0 ];then systemctl restart containerd;fi
chmod a+x init-kube.sh
sh init-kube.sh
```

### Relevant log output?

```Shell
mount rootfs failed exec init.sh failed failed to execute command(cd /var/lib/sealer/data/my-cluster/rootfs  && chmod +x scripts/* && cd scripts && bash init.sh /var/lib/docker sea.hub 5000) on host(10.9.1.10): error(exit status 1)
```

### What is the version of Sealer you using?

{"gitVersion":"v0.8.5","gitCommit":"f9c3d99","buildDate":"2022-04-28 14:16:58","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

Ubuntu 21.04

### What is the Kernel version?

Linux tjpt-master 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by zhy76** [comment]
I have the same problem and find it is because the init-kube.sh file “systemctl enable kubelet” command, which is executed with a "file exists" error. This can be solved by using the “systemctl disable kubelet” command on the node.And this bug is because the environmental data is not clear.

**Comment by allencloud** [comment]
@clcc2019 Could you search the log above your pasted picture and find some abnormal and error log? 

@zhy76 Could you attach some detailed error message here in this issue?

**Comment by zhy76** [comment]
> 

yes,the error message is like this:
![image](https://user-images.githubusercontent.com/56665618/192785868-b18c2e52-826d-40d9-96be-05bc3e2a49aa.png)
and I finanlly found the error is caused by the command "systemctl enable kubelet" and  the error is solved by executing the command "systemctl disable kubelet"
![image](https://user-images.githubusercontent.com/56665618/192786653-febed367-268f-4e3f-9245-9136dda8d8b1.png)

**Comment by zhy76** [comment]
I see that the command "systemctl disable kubelet" has been added to clean.sh.The reason for this problem is that the image is not updated.
![image](https://user-images.githubusercontent.com/56665618/192802617-12e0f9f2-1484-4488-a655-170f6c24588d.png)
