### ISSUE TITLE
Build ClusterImage is different from the old way, images registry is empty!

### ISSUE THREAD

**Issue by starComingup** [sealerio/sealer#1735]
### What happen?

The old way which we build clusterImage, The kubefile just like:
```dockerfile
FROM scratch
COPY rootfs/* .
COPY ${ARCH}/* . 
COPY imageList manifests
```
And it will pull the component images automatically which specified in `imageList` and build it into clusterImage.
But in the latest code with buildah, we need to save images manually. It seems a big different with old way before sealer v0.8.6.
And the new way which we build the base clusterImage's Kubefile would like:
```dockerfile
FROM scratch
COPY rootfs/ .
COPY amd64/ .
COPY imageList manifests
```
Although it follow the dockerfile opinion, the image would not pull images automatically, this make me confuse.

### Relevant log output?

```Shell
NONE
```

### What you expected to happen?

I want the sealer build could pull the images as old way

### What is the version of Sealer you using?

the latest code in main

### What is your OS environment?

Any

### What is the Kernel version?

Any

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by starComingup** [comment]
@justadogistaken Looking forward to your reply 😄

**Comment by justadogistaken** [comment]
Are you saying that the specified images from imageList would not be pulled automatically? I'm a bit confused because you list two kubefiles. I'm not sure what you are trying to say.

**Comment by justadogistaken** [comment]
I think the problem is resulted from this line:
```
COPY imageList manifests
```

If manifests does not exist before.
This line will rename imageList to manifests instead of putting imageList under manifests.
You should do `COPY imageList manifests/`

**Comment by starComingup** [comment]
> I think the problem is resulted from this line:
> 
> ```
> COPY imageList manifests
> ```
> 
> If manifests does not exist before. This line will rename imageList to manifests instead of putting imageList under manifests. You should do `COPY imageList manifests/`

What a nice solution! In latest code of sealer(after v0.8.6), If we want to specify our image in base clusterImage. we would use `COPY imageList manifests/`.
