### ISSUE TITLE
vendor kubeadm/v1beta2 rather than directly import this golang file

### ISSUE THREAD

**Issue by allencloud** [sealerio/sealer#1743]
## Issue Description

We found that file https://github.com/sealerio/sealer/blob/main/pkg/runtime/kubernetes/kubeadm/v1beta2/types.go is in sealer's repo code. Actually we should use vendor to import this file of code.

### Describe what feature you want

vendor kubeadm/v1beta2 package as we could.

I tried this, while unfortunately I failed.  😨

**Comment by zhy76** [comment]
Maybe I can try to solve this issue.

**Comment by zhy76** [comment]
Maybe I can try to solve this issue.

**Comment by allencloud** [comment]
> Maybe I can try to solve this issue.

So great. Thanks for your work in advance. @zhy76
