### ISSUE TITLE
sealer pull kubernetes err 

### ISSUE THREAD

**Issue by mahmut-Abi** [sealerio/sealer#1766]
### What happen?

I can search kubernetes cluster image by 'sealer search kubernetes'. then i got an error.

### Relevant log output?

```Shell
➜  linux_amd64 git:(main) sudo sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.17.17
Trying to pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.17.17...
Usage:
  sealer pull [flags]

Examples:
sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8
sealer pull registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8 --platform linux/amd64


Flags:
  -h, --help              help for pull
      --platform string   prefer OS/ARCH instead of the current operating system and architecture for choosing images (default "linux/amd64")
      --policy string     missing, always, ifnewer or never. (default "always")

Global Flags:
      --color string               set the log color mode, the possible values can be [never always] (default "always")
      --config string              config file of sealer tool (default is $HOME/.sealer.json)
  -d, --debug                      turn on debug mode
      --hide-path                  hide the log path
      --hide-time                  hide the log time
      --log-to-file                write log message to disk
  -q, --quiet                      silence the usage when fail
      --remote-logger-url string   remote logger url, if not empty, will send log to this url
      --task-name string           task name which will embedded in the remote logger header, only valid when --remote-logger-url is set

2022-10-11 16:04:30 [ERROR] [root.go:77] sealer-unknown: copying system image from manifest list: initializing image from source docker://registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.17.17: unsupported docker v2s2 media type: "application/octet-stream"
```

### What you expected to happen?

fix it.

### How to reproduce it (as minimally and precisely as possible)?

```YAML
sealer version: 
{"gitVersion":"unknown","gitCommit":"a20019af","buildDate":"2022-10-11 16:14:40","goVersion":"go1.18.6","compiler":"gc","platform":"linux/amd64"}
commit id:a20019af34aff02a96c45cd409779e52fad1a9c0
kernel: 5.15.45-amd64-desktop
```

### Anything else we need to know?

nothing

### What is the version of Sealer you using?

{"gitVersion":"unknown","gitCommit":"a20019af","buildDate":"2022-10-11 16:14:40","goVersion":"go1.18.6","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

[Version]  SystemName=Deepin SystemName[zh_CN]=深度操作系统 ProductType=Desktop ProductType[zh_CN]=桌面 EditionName=Community EditionName[zh_CN]=社区版 MajorVersion=20 MinorVersion=20.7 OsBuild=11038.007

### What is the Kernel version?

5.15.45-amd64-desktop

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by mahmut-Abi** [comment]
but i can pull cluster image from harbor which i push using sealer v0.8.6.

**Comment by justadogistaken** [comment]
@mahmut-Abi 
The new sealer version has large change on image storage. So It may not be able to support old image.
But with this change, a lot of problems before will not happen again. And the image will be stable in the next couple of years.

**Comment by mahmut-Abi** [comment]
thank
