### ISSUE TITLE
 failed to find image by name: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.22.5

### ISSUE THREAD

**Issue by baozitao** [sealerio/sealer#1776]
### What happen?

sealer run kubernetes:v1.22.5   --masters 10.0.0.135,10.0.0.140   --nodes 10.0.0.103,10.0.0.108,10.0.0.11
然后

[ERROR] [root.go:70] sealer-v0.8.6: failed to find image by name: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.22.5

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
pls use the latest official cluster image: https://github.com/sealerio/sealer#user-guide
