### ISSUE TITLE
官网教学，错误真的太多了，建议找个人改一下，靠那点教学，根本用不起来，直接放弃

### ISSUE THREAD

**Issue by baozitao** [sealerio/sealer#1777]
### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by allencloud** [comment]
Thanks for your feedback. The website guidance has inconsistency content indeed. If you need any help, perhaps currently seeking them from dingtalk group is the most efficient way. Sorry for the bothering the website doc brings. @baozitao
