### ISSUE TITLE
when I run ‘sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.20.15-test’, the tigera-operator didn't run

### ISSUE THREAD

**Issue by zhy76** [sealerio/sealer#1800]
### What happen?

when I run ‘sealer run registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.20.15-test’, the tigera-operator didn't run.
<img width="537" alt="1666601826344_B4561703-7823-456d-989F-9272D168CCDF" src="https://user-images.githubusercontent.com/56665618/197506358-cb86d897-1a0a-4e7c-925f-62c24897d68f.png">
the log of tigera-operator:
<img width="640" alt="lQLPJxbO0OZaBeh5zQT_sJWwYev4BfnIA1Pp5hhApAA_1279_121" src="https://user-images.githubusercontent.com/56665618/197505988-8df7a4e5-b8f6-42cb-8ed1-13f6840b4136.png">
the nodes are not ready:
<img width="418" alt="lQLPJxbO0fH59-tozQNDsF-oKFMlahy3A1PrnFYAHQA_835_104" src="https://user-images.githubusercontent.com/56665618/197506295-532d77ae-b7eb-40d3-8bdb-2f22db8bd8cf.png">
the svc :
<img width="492" alt="1666601701785_2C2E7F22-9DCF-4dca-9C89-03047896E799" src="https://user-images.githubusercontent.com/56665618/197506153-0feac59b-e5cb-4413-8c83-c56a1400efa6.png">
we found that the kube-proxy is not running:
<img width="582" alt="1666603165711_323EB929-9A14-4562-85AB-A209851CE33B" src="https://user-images.githubusercontent.com/56665618/197506820-653ec43b-b5b9-42bf-9532-79861a835cf0.png">
we found that it is bacause of the podSecurityPolicy:
![image](https://user-images.githubusercontent.com/56665618/197507166-ea2afe87-8ada-4ec3-8b9f-4a0a1a643cc7.png)
<img width="821" alt="1666603368226_933E97BC-8BB5-47ca-A82D-CF3399FC979E" src="https://user-images.githubusercontent.com/56665618/197509037-1749930f-821d-449c-b5c5-4786e97a1cbe.png">
and we deleted enable-admission-plugins:
<img width="626" alt="1666603678810_25675B11-BCA3-428d-9105-5DC78E23B9A8" src="https://user-images.githubusercontent.com/56665618/197508969-34b7fa3e-61b1-44a6-a465-ed277c2c3e1f.png">
but some pods still did not running:
![image](https://user-images.githubusercontent.com/56665618/197509381-4b3bda84-4a6c-42c8-978f-a8961c4bbeaf.png)
it is mainly baccause Back-off pulling image "sea.hub:5000/sealer/lvscare:v1.1.3-beta.8":
![image](https://user-images.githubusercontent.com/56665618/197509540-f42a1e38-9b4a-41a0-acda-7267c1e7444a.png)

### What you expected to happen?

Fix the images registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.20.15-test,and after sealer run the nodes are ready

### What is your OS environment?

Ubuntu 20.04

### What is the Kernel version?

Linux VM-12-6-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by jsparter** [comment]
#1768

**Comment by justadogistaken** [comment]
@kakaZhou719 @Stevent-fei

**Comment by justadogistaken** [comment]
The problem of "timeout" is derived from "PodSecurityPolicy". 
@Stevent-fei @kakaZhou719 Is it enabled by default? Maybe we need to remove the option or add some proper "PodSecurityPolicy".

**Comment by kakaZhou719** [comment]
already build latest official cluster image: https://github.com/sealerio/sealer#user-guide
