### ISSUE TITLE
Bug: if run fail, need clean /var/lib/sealer/data/linux_amd64_ manualy

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1801]
### What happen?

![image](https://user-images.githubusercontent.com/23137196/197527394-be8b5b38-b402-4c48-baa6-5af29127d882.png)

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by zhy76** [comment]
Maybe I can help
