### ISSUE TITLE
If join a node fail, it will be stored in ClusterFile and can't join it again, unless remove it from ClusterFile manually.

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1802]
### What happen?

![image](https://user-images.githubusercontent.com/23137196/197527487-90cd788b-c37d-468f-8243-631e1ff2ae05.png)

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by zhy76** [comment]
I can help to solve this.
