### ISSUE TITLE
support  sealer cmd `sealer scaleup -f clusterfile`

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1806]
## Issue Description

Type: *feature request*

### Describe what feature you want

`sealer scaleup -f clusterfile`: will scale up the cluster node with differ between clusterfile and current cluster.

**Comment by justadogistaken** [comment]
@kakaZhou719 
Could you help add more info for this feature?
Is there the `scaledown` should be supported too?
I hope that the more info contains background and scenes.

**Comment by kakaZhou719** [comment]
> @kakaZhou719 Could you help add more info for this feature? Is there the `scaledown` should be supported too? I hope that the more info contains background and scenes.

this sub cmd only do scaleup thing, equivalent to `sealer join`,  This is because `join` are emitted from node, and sealer `scaleup` are emitted from the cluster compared with kubeadm join.  What about your suggestion？

**Comment by justadogistaken** [comment]
But I think it also could be achived by `sealer join -f ...`? Do we really need to come up with a new sub command?
