### ISSUE TITLE
Store the installation information of cluster applications

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1807]
## Issue Description

Type: *feature request*

### Describe what feature you want

It is very convenient for user to know which cluster application was launched.

**Comment by justadogistaken** [comment]
@kakaZhou719 It's too simple to be understood.
I wish there will be more information to describe why we need this and simple implementation.
In that case, we may be able involve  community to help us to develop this feature.

**Comment by kakaZhou719** [comment]
> @kakaZhou719 It's too simple to be understood. I wish there will be more information to describe why we need this and simple implementation. In that case, we may be able involve community to help us to develop this feature.

 If user want to migrate clustered applications, they can do it according to this applications  installation information.
However, we need to design a better structure to store it。
