### ISSUE TITLE
大佬们，想问下目前有什么交流群吗？好像现在的都加不了了

### ISSUE THREAD

**Issue by ouweijun1** [sealerio/sealer#1822]

**Comment by allencloud** [comment]
@Starnop @VinceCui I found that picture in https://github.com/sealerio/sealer#communication-channels seems invalid. Could you please update that dingtalk scan code? 

@ouweijun1 You could add dingtalk group by group number:  34619594 .

**Comment by ouweijun1** [comment]
> @Starnop @VinceCui我发现[https://github.com/salerio/sealer#communication-channels](https://github.com/sealerio/sealer#communication-channels)中的图片似乎无效。你能更新那个钉钉扫描码吗？
> 
> @ouweijun1您可以按组号添加钉钉组： 34619594 。

进来了，谢谢

**Comment by Starnop** [comment]
I will update the dingtalk scan code ASAP

**Comment by Starnop** [comment]
has been updated

And I will close this issue. Welcome to keep talking if you have any questions. @ouweijun1
