### ISSUE TITLE
[proposal] image command line user guidance

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1834]
## Issue Description

Type: *feature request*

# image cli

## build image

if not set platform will only build default platform images:
cmd: `sealer build -f Kubefile -t my-image:v1`

build multi-arch platform image:
cmd: `sealer build -f Kubefile -t my-image:v1 --platform linux/amd64,linux/arm64`

## list image

list all images: also could support output sort .

cmd `sealer images`
```shell
+--------------------+------------------------------------------------------------------+-------+---------+---------------------+-----------+
|     IMAGE NAME     |                             IMAGE ID                             | ARCH  | VARIANT |       CREATE        |   SIZE    |
+--------------------+------------------------------------------------------------------+-------+---------+---------------------+-----------+
| kubernetes:v1.20.4 | 647609b35952a79d14b0c7cbdb03134a65e092bd5a66d502fcb11bd882e586eb | amd64 |         | 2022-11-03 11:15:58 | 954.78MiB |
| kubernetes:v1.20.4 | 6eaf498c02b73ae494b1a8ac738332fa0799d15f4fb4d51269572f72226cb70b | arm64 | v8      | 2022-11-03 11:15:19 | 835.01MiB |
+--------------------+------------------------------------------------------------------+-------+---------+---------------------+-----------+
```

## inspect image

inspect all platforms at local store:
cmd: `sealer inspect my-image:v1`

inspect specific platform such as arm64:
cmd: `sealer inspect my-image:v1 --platform linux/arm64`

## push image

push all platforms at local store:
cmd: `sealer push my-image:v1 docker.io/sealer/my-kubernetes:1.19.8`

push specific platform such as arm64:
cmd: `sealer push my-image:v1  docker.io/sealer/my-kubernetes:1.19.8 --platform linux/arm64`

## pull image

pull all platforms:
`sealer pull docker.io/sealer/my-kubernetes:1.19.8`

pull specific platform such as arm64:
`sealer pull docker.io/sealer/my-kubernetes:1.19.8 --platform linux/arm64`

## save image

save all platforms:
`sealer save -o kubernetes.tar kubernetes:v1.19.8`

save specific platform such as arm64:
`sealer save -o kubernetes.tar kubernetes:v1.19.8 --platform linux/arm64`

## load image

just load it, no need to care about its platform,but we can merge the same image with different platform.
cmd: `sealer load -i kubernetes.tar`

## tag image
tag will tag manifest list,image id will not be changed.
`sealer tag kubernetes:v1.19.8 registry.cn-qingdao.aliyuncs.com/sealer-apps/kubernetes:v1.19.8`

## delete image

delete all platforms:
`sealer rmi kubernetes:v1.19.8`

delete specific platform such as arm64:
`sealer rmi kubernetes:v1.19.8 --platform linux/arm64`

**Comment by kakaZhou719** [comment]
@justadogistaken @starComingup @VinceCui , pls help us to review.

**Comment by starComingup** [comment]
> @justadogistaken @starComingup @VinceCui , pls help us to review.

Does this guidance mean that I use `sealer build\inspect\and-so-on -h` would hint me the following using info. Or it just for command design, I think it close with docker, so i am very familiar with it.

BTW, In cmd `build`, maybe we could set flag `-f` default value as Kubefile.

**Comment by kakaZhou719** [comment]
> > @justadogistaken @starComingup @VinceCui , pls help us to review.
> 
> Does this guidance mean that I use `sealer build\inspect\and-so-on -h` would hint me the following using info. Or it just for command design, I think it close with docker, so i am very familiar with it.
> 
> BTW, In cmd `build`, maybe we could set flag `-f` default value as Kubefile.

yes, it is a command design about how to use sealer image cli.
