### ISSUE TITLE
detach the raw image data from rootfs

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1846]
## Issue Description

At present, our cluster image data is mixed with application image data and base image data, If we run multiple images at the same time, there will be conflicts.
So we suggest that we separate the different cluster image data.

1. detach the registry data from rootfs
2. detach the application  data from rootfs

# build stage

## base fs directory tree

base fs will package all the dependencies refers to the kubernetes cluster requirements.

```shell yaml
├── bin
├── cri
├── etc
├── images # registry docker image, will load this image and run a local registry in cluster
├── Kubefile
├── registry # will saved all container image data.
├── scripts
├── plugins 
├── statics # yaml files, sealer will render values in those files
└──... # others image context.
```

## application directory tree

```shell yaml
├── nginx # will save application context,such as yaml file or charts packages.
├── Kubefile
├── registry # will saved all container image data.
├──... # others application context
```

# run stage

### base fs directory tree

all base fs directory will under below directory:
`/var/lib/sealer/data/mount/${imageName}/${platform}`

### application directory tree

all base fs directory will under below directory :
`/var/lib/sealer/data/mount/${imageName}/${platform}`

### base fs directory tree

`/var/lib/sealer/data/${cluster name}/rootfs`

### application directory tree

`/var/lib/sealer/data/${cluster name}/applications`

### cluster cert directory tree

`/var/lib/sealer/data/${cluster name}/pki/`

#### registry config directory tree

```yaml
/var/lib/sealer/data/${cluster name}/registry/etc/
├── registry_config.yml # config file for registry
└── registry_htpasswd  # auth info for registry if needed
```

#### registry data directory tree

```yaml
/var/lib/sealer/data/${cluster name}/registry/data/
└── docker
└── registry
└── v2
├── blobs
└── repositories
```

#### registry cert directory tree

```yaml
/var/lib/sealer/data/${cluster name}/registry/certs/
├── sea.hub.crt
└── sea.hub.key
```

**Comment by kakaZhou719** [comment]
1. do not support scan manifest dir to download container images,user could specify imagelist to download extra container images
2. base image do not support install applications
3. registry component remove from rootfs: include certs,config,data.
4. cluster pki certs remove from rootfs

**Comment by jsparter** [comment]
Is pr #1850 doing part of this issue?

**Comment by kakaZhou719** [comment]
> Is pr #1850 doing part of this issue?

yes, only split mounted dir with image name. the rest of work is waiting for the normalization of the basefs directory drafted by @Starnop .
