### ISSUE TITLE
Sealer fails to deploy k8s cluster on rocky linux

### ISSUE THREAD

**Issue by BearDare** [sealerio/sealer#1853]
### What happen?

I use sealer to deploy k8s cluster on rocky linux, it fails. 
enable debug,I found an error when starting  the sealer-registry.

The following is the system related information
kernal: 5.14.0-70.13.1.el9_0.x86_64
os: Rocky Linux release 9.0 (Blue Onyx)
k8s version: v1.21.14
docker version: 19.03.14-sealer
sealer: v0.8.6

### Relevant log output?

```Shell
+ docker run -d --restart=always --net=host --name sealer-registry -v /var/lib/sealer/data/my-cluster/rootfs/certs:/certs -v /var/lib/sealer/data/my-cluster/rootfs/registry:/var/lib/registry -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/sea.hub.crt -e REGISTRY_HTTP_TLS_KEY=/certs/sea.hub.key registry:2.7.1
docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
+ startRegistry
+ n=1
+ ((  n <= 3  ))
+ echo 'attempt to start registry'
attempt to start registry
+ docker start sealer-registry
Error response from daemon: OCI runtime create failed: container with id exists:: unknown
Error: failed to start containers: sealer-registry
```

### What you expected to happen?

I want k8s cluster to deploy correctly

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/19593951/201301233-6bcf9997-ced0-4113-b72c-d6360448384d.png)

### What is the version of Sealer you using?

v0.8.6

### What is your OS environment?

Rocky Linux release 9.0 (Blue Onyx)

### What is the Kernel version?

5.14.0-70.13.1.el9_0.x86_64

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Stevent-fei** [comment]
@BearDare I think it's a system compatibility issue.
Try using centos or ubuntu?

**Comment by Stevent-fei** [comment]
@BearDare I think it's a system compatibility issue.
Try using centos or ubuntu?

**Comment by Starnop** [comment]
@BearDare Cloud you please make sure that you can use the docker community Version `19.03.14` normally on your operating system?

**Comment by BearDare** [comment]
> @BearDare Cloud you please make sure that you can use the docker community Version `19.03.14` normally on your operating system?
Thanks, I konw why.
because docker engine 20.10 support cgroup v2. 
The built-in docker version of sealer is 19.03.14-sealer.
This issus can be closed
