### ISSUE TITLE
support run-app with the specified application name

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#1888]
## Issue Description

Currently, our cluster image could contains multiple applications at image extension, so we could support run-app with the specified application name like :
`sealer run-app --app-name mysql my-cluster:v1`

this will only launch mysql application in cluster image "my-cluster:v1" .

if "--app-name mysql" not set ,will run its default application in cluster image "my-cluster:v1" .

Type: *feature request*

**Comment by Stevent-fei** [comment]
@kakaZhou719 I will finish this feature this week (2022.11.25)

**Comment by kakaZhou719** [comment]
Already supported in Clusterfile
