### ISSUE TITLE
Kubefile 中COPY参数是都可以友好的提示?

### ISSUE THREAD

**Issue by zzq1314zll** [sealerio/sealer#1897]
### What happen?

<img width="1760" alt="image" src="https://user-images.githubusercontent.com/33930711/204255381-af00fe74-c377-4e52-a0d1-ce58565b212c.png">
其实这是我COPY 参数写错例如
```shell
COPY install.yaml .
````
我忘记写. 了，如下:
```shell
COPY install.yaml 
```
这个时候就会出现上面的错误

### What is the version of Sealer you using?

{"gitVersion":"v0.8.6","gitCommit":"884513e","buildDate":"2022-07-12 02:58:54","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="CentOS Linux"

### What is the Kernel version?

Linux k8s-01 5.19.6-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 29 10:06:03 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Starnop** [comment]
@Stevent-fei PTAL, THX

**Comment by Stevent-fei** [comment]
@zzq1314zll ok,this message prompt will be fixed in the new version

**Comment by kakaZhou719** [comment]
fixed at 	 https://github.com/sealerio/sealer/blob/b790c7720e0aab694b94386c142bb32e27152bbd/build/kubefile/parser/kubefile.go#L216
