### ISSUE TITLE
sealer暴露的命令行梳理

### ISSUE THREAD

**Issue by Stevent-fei** [sealerio/sealer#1905]
| alpha列表 |                   用途                        |        当前状态       |建议处理方式 |
| :-----   | :---------------------------------------------| :-------------------|-----------|
| check    |  查询集群的状态信息,包括node状态,服务状态和pod状态    |         ✅          |   无      |
| debug    |  debug模式，可以输出更多的信息                     |         ✅           |   无      |
| exec     |  在指定节点上执行shell命令或脚本                   |         ✅             |   无      |
| gen      |  Sealer将调用kubernetes API来获取主机和节点的IP信息，然后生成一个Clusterfile。并拉一个匹配kubernetes版本的ClusterImage         |        ❌            |     待定      |
| merge    |  Sealer合并命令将源图像的所有层合并为一个目标图像     |         ❌           |    待定       |
| upgrade  |  升级集群                                                            |         ❌            |    待定       |
| search   |  查看默认docker hub中所支持的镜像                  |         ✅           |     无      |
| mount | 挂载镜像目录，可检测与构建时的一致性                 |         ✅           |     无 [已完成]      |
|umount| 删除镜像目录                                                              |         ✅           |     无 [已完成]     |
| manifest |  构建多架构镜像                                               |         ✅           |    文档不透出，@周磊 待确认，干掉/放到 alpha 里 [已迁移]     |
| run-app  |  只运行app操作                                 |        ✅         |     干掉这个命令，run 增加 flag，支持 run 集群+应用镜像，只运行镜像的场景[已迁移，等待其他pr合入，然后解决冲突]      |

| cluster列表 |                   用途                        |        当前状态       |建议处理方式 |
| :-----   | :---------------------------------------------| :-------------------|-----------|
| apply    |  运行集群操作(Clusterfile方式启动集群)             |        ✅             |   无      |
| cert     |  修改证书操作                                    |        ✅              |   增加描述，非立即生效 @VinceCui         |
| delete   |  删除集群操作                                    |        ✅             |    无       |
| join     |  加入节点操作                                    |        ✅             |   文档不透出，能力标记为 deprecated，建议使用 scale-up        |
| run      |  运行集群+应用 ,如果只有应用，没有集群会部署失败                                 |        ✅           |   无        |
| scale-up |  scale-up节点操作                               |        ✅        |    无       |

| image列表 |                   用途                        |        当前状态       |建议处理方式 |
| :-----   | :---------------------------------------------| :-------------------|-----------|
| build    |  查询集群的状态信息,包括节点状态,服务状态和吊舱状态    |         ✅             |   无      |
| images   |  查看当前本地集群镜像操作                          |         ✅             |    无       |
| inspect  |  查看集群详细信息                                |          ✅             |    无       |
| load     |  从.tar结尾的压缩包中加载集群                      |         ✅             |    无       |
| login    |  登录                                          |         ✅             |    无       |
| logout   |  登出                                          |         ✅            |   无        |
| pull     |  从镜像仓库拉取镜像                              |          ✅            |     无      |
| push     |  上传镜像到镜像仓库                              |          ✅            |     无      |
| rmi      |  删除本地镜像                                   |          ✅             |     无      |
| save     |  保存镜像，格式是以.tar结尾的压缩包                |           ✅            |      无     |
| tag      |  修改本地镜像tag                                |           ✅            |     无      |

**Comment by kakaZhou719** [comment]
task is done.
