### ISSUE TITLE
CMD apply test.yaml cause default serviceaccount already exist,  why apply cause already exist error

### ISSUE THREAD

**Issue by ZhengJuCn** [sealerio/sealer#1912]
### What happen?

exec sealer apply -f Clusterfile

when exec "CMD apply test.yaml"

cause error message "default serviceaccount already exist"

 why apply cause already exist error

### What you expected to happen?

just apply success like kubectl apply

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
> @kakaZhou719 could you please help?
Can you see which service account is already exists ? Or provide your test.yaml  and clusterfile ?

**Comment by ZhengJuCn** [comment]
@kakaZhou719  default serviceacount, actually do exist, but i want to patch default serviceaccount,  in manual exec kubectl apply   not cause any error.
but in sealer apply  CMD kubectl apply will cause already exist error

**Comment by kakaZhou719** [comment]
which sealer version you used? and cluster image name. i will try to investigate this issue.

**Comment by ZhengJuCn** [comment]
@kakaZhou719
sealer: v0.8.6
baseimage: kubernetes:v1.19.9 then build cluster image with Kubefile

wild, i simpfiy test:
build cluster image with kubernetes:v1.19.9 Copy just sa.yaml CMD kubectl apply , not cause already exist error......

when i use real cluster image:
Error from server (AlreadyExists): error when creating "manifests/test/some.yaml": serviceaccounts "default" already exists

**Comment by ZhengJuCn** [comment]
[root@master-0 ]# cd /var/lib/sealer/data/my-cluster/rootfs && kubectl apply -f manifests/test
namespace/test unchanged
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
serviceaccount/default configured

when i manual ssh this node & exec failed command, every thing ok@kakaZhou719
