### ISSUE TITLE
An error occurred at   sealer build 

### ISSUE THREAD

**Issue by henkuaifacai** [sealerio/sealer#1913]
### What happen?

我在用sealer 制作基础镜像时在里面放了一个chart包(charts/vela-core)，然后build时解析这个包的镜像时有问题，解析出一个错误的包
docker.io/library/parameter.image:latest
docker.io/library/parameter.image:latest
实际上没有这些包

### Relevant log output?

```Shell
[root@master01 builad]# sealer  build  -t  testtest:1.0.2  . 
2022-12-08 18:05:04 [INFO] [utils.go:135] get mount dir :/var/lib/sealer/tmp/.DTmp-061589638 success 
2022-12-08 18:05:04 [INFO] [executor.go:123] start to check the middleware file
2022-12-08 18:05:04 [INFO] [executor.go:63] run build layer: COPY . .
2022-12-08 18:05:05 [INFO] [executor.go:95] exec all build instructs success
Pulling image: docker.io/kubernetesui/dashboard:v2.6.1
Pulling image: docker.io/kubernetesui/metrics-scraper:v1.0.8
Pulling image: docker.io/library/parameter.image:latest
Pulling image: docker.io/library/string:latest
Pulling image: docker.io/library/_params.image:latest
Pulling image: docker.io/oamdev/vela-core:v1.6.4
Pulling image: docker.io/oamdev/kube-webhook-certgen:v2.4.1
```

### What you expected to happen?

后期能不能加一些选项，比如忽略一些错误的镜像

### How to reproduce it (as minimally and precisely as possible)?

```YAML
FROM kubernetes:v1.24.6
COPY . .
CMD cp -ar bin/helm   /usr/local/bin/ && cp -ar bin/vela   /usr/local/bin/

CMD helm install --create-namespace -n vela-system kubevela charts/vela-core --wait  &&  vela addon enable velaux
CMD  kubectl  apply -f  manifests/recommended.yaml
```

### What is the version of Sealer you using?

{"gitVersion":"v0.8.6","gitCommit":"884513e","buildDate":"2022-07-12 02:58:54","goVersion":"go1.16.15","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

CentOS Linux 7 (Core)

### What is the Kernel version?

Linux master01 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@henkuaifacai ，看来应该是在walk 这个charts包的时候，找到了错误的镜像list，能看下这个`docker.io/library/parameter.image:latest` 在包的哪里吗？

**Comment by kakaZhou719** [comment]
@henkuaifacai ，#2020 is working on it.
