### ISSUE TITLE
taint plugin don't execute

### ISSUE THREAD

**Issue by sunshinejdq** [sealerio/sealer#1914]
### What happen?

[root@master-0 ~]#  cat Kubefile 
FROM kubernetes:v1.20.0
COPY metrics-server.yaml .
CMD kubectl apply -f metrics-server.yaml

[root@master-0 ~]# cat Clusterfile
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: jdq-cluster
spec:
  image: taint_test:v2.1
  hosts:
    - ips: [ 172.30.10.163 ]
      roles: [ master ]
  ssh:
    passwd: "ka0@2021"
    user: root
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: taint
spec:
  type: TAINT
  action: PreGuest
  data: |
    172.30.10.163 node-role.kubernetes.io/master:NoSchedule-

![image](https://user-images.githubusercontent.com/5857762/206991256-4a1d017d-815e-4f21-9761-abd0528aabaa.png)

The taint plugin is not executed and no error is reported.

![image](https://user-images.githubusercontent.com/5857762/206991557-1e775ffd-0fe3-4f09-80cd-90b823033981.png)

### Relevant log output?

```Shell
No errors is reported.
```

### What is the version of Sealer you using?

v0.8.6 and v0.8.5

### What is your OS environment?

centos 7

### What is the Kernel version?

Linux master-0 3.10.0-1127.19.1.el7.x86_64

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Stevent-fei** [comment]
@sunshinejdq #1854

**Comment by kakaZhou719** [comment]
@sunshinejdq , seems this bug is already fixed. i will close this issue, pls feel free to contact us if you have any questions
