### ISSUE TITLE
Don't use : to join host and port, use net.JoinHostAndPort, cause IPv6

### ISSUE THREAD

**Issue by VinceCui** [sealerio/sealer#1920]
### What happen?

![image](https://user-images.githubusercontent.com/23137196/208233467-d92c81d3-5b62-44e7-9737-fe3954785524.png)

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
https://github.com/sealerio/sealer/pull/1924 fixed this issue
