### ISSUE TITLE
sealer images: show my docker images

### ISSUE THREAD

**Issue by clcc2019** [sealerio/sealer#1933]
### What happen?

sealer images: show my docker images,Unable to list cluster mirrors

### What is the version of Sealer you using?

{"gitVersion":"v0.9.0","gitCommit":"3f444e6","buildDate":"2022-12-23 02:58:39","goVersion":"go1.17.13","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

Ubuntu 22.04 LTS

### What is the Kernel version?

Linux master 5.15.0-53-generic

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Starnop** [comment]
@clcc2019 It's incredible. Could you please show some screenshot information？

**Comment by clcc2019** [comment]
> @clcc2019 It's incredible. Could you please show some screenshot information？

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/46099295/210332735-436ef0b1-ee42-44f6-9d5b-c32857155dcf.png">

**Comment by clcc2019** [comment]
sealer v0.8.6
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/46099295/210333019-56c9df1f-bd4d-4f91-a900-91b2d6a8ae78.png">

**Comment by kakaZhou719** [comment]
@clcc2019 ,thats because sealer using buildah as its image engine. whose client who use buildah will share the same local storage. i will close this issue ,if you have any questions ,pls feel free to contact us.
