### ISSUE TITLE
Sealer apply is not really an apply operation

### ISSUE THREAD

**Issue by Starnop** [sealerio/sealer#1944]
### What happen?

Reexecute `sealer apply` a kube-installer image will only check the cluster node and the relevant parts of the application are not checked. Imagine a scenario:

1. I run a kube-installer image that contains  `APP1` v1
2. I run an app-installer image that contains `APP1` v2
3. I re-run the kube-installer image from step 1 again, what should happen?

![image](https://user-images.githubusercontent.com/31209634/210399071-a98a803c-621e-4b23-8972-558ce4f2301b.png)

### What is the version of Sealer you using?

sealer 0.9.0

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
fixed at v0.9.2
