### ISSUE TITLE
app image don't pull images from build-in registry

### ISSUE THREAD

**Issue by jsparter** [sealerio/sealer#1952]
### What happen?

Following [Quik start](http://sealer.cool/docs/getting-started/quick-start.html#prerequisites), build an app image and run it, `nginx:latest` will packed in the app image at build stage, but when running the app image, docker still pull `nginx:latest` from dockerhub not build-in registry even if `nginx:latest` appeard in build-in registry.
Can kyverno solve this problem? @YTGhost 

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Starnop** [comment]
> Can kyverno solve this problem? @YTGhost

Sure
