### ISSUE TITLE
"sealer run -f Clusterfile" report errors

### ISSUE THREAD

**Issue by sunshinejdq** [sealerio/sealer#1956]
### What happen?

"sealer run -f Clusterfile" report errors
-------------
cat Clusterfile
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
  name: jdq-cluster
spec:
  image: localhost/testshell:1.0 
  hosts:
    - ips: [ 172.30.10.163 ]
      roles: [ master ]
    - ips: [ 172.30.10.53,172.30.10.63,172.30.10.73,172.30.10.83 ]
      roles: [ node ]  
  ssh:
    passwd: "k***1"
    user: root

### Relevant log output?

```Shell
2023-01-05 18:48:40 [INFO] [pull.go:79] ace990753d28972246278aa6b52767fa0a98304f556ca933ba1c7a01c2dbeb40

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sealerio/sealer/cmd/sealer/cmd/cluster.NewRunCmd.func1(0xc000574c80, {0xc0000b1ea0, 0x0, 0x2})
        /home/runner/work/sealer/sealer/src/github.com/sealerio/sealer/cmd/sealer/cmd/cluster/run.go:141 +0x7c6
github.com/spf13/cobra.(*Command).execute(0xc000574c80, {0xc0000b1e80, 0x2, 0x2})
        /home/runner/work/sealer/sealer/src/github.com/sealerio/sealer/vendor/github.com/spf13/cobra/command.go:872 +0x624
github.com/spf13/cobra.(*Command).ExecuteC(0x49647e0)
        /home/runner/work/sealer/sealer/src/github.com/sealerio/sealer/vendor/github.com/spf13/cobra/command.go:990 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/sealer/sealer/src/github.com/sealerio/sealer/vendor/github.com/spf13/cobra/command.go:918
github.com/sealerio/sealer/cmd/sealer/cmd.Execute()
        /home/runner/work/sealer/sealer/src/github.com/sealerio/sealer/cmd/sealer/cmd/root.go:74 +0x25
main.main()
        /home/runner/work/sealer/sealer/src/github.com/sealerio/sealer/cmd/sealer/main.go:32 +0x36
```

### What is the version of Sealer you using?

0.9

### What is your OS environment?

centos 7

### What is the Kernel version?

3.10.0-1160.81.1.el7.x86_64

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@sunshinejdq , seems this bug is already fixed. i will close this issue, pls feel free to contact us if you have any questions .
