### ISSUE TITLE
[BUG] An app cannot contain different types of files

### ISSUE THREAD

**Issue by YTGhost** [sealerio/sealer#1993]
### What happen?

I have written a Kubefile containing the nginx app, which contains a yaml file and a shell file. When executing `sealer build`, the build reports an error.
```
[ERROR] [root.go:75] sealer-v0.9.1: failed to judge the application type for nginx: mixed app type is not supportted
```

### What you expected to happen?

Allowing an app to contain different files

### How to reproduce it (as minimally and precisely as possible)?
Kubefile
```YAML
FROM docker.io/sealerio/kubernetes:v1.22.15
APP nginx local://install.yaml local://test.sh
APPCMDS nginx ["kubectl apply -f install.yaml && sh test.sh"]
LAUNCH ["calico", "nginx"]
```

### What is the version of Sealer you using?

{"gitVersion":"v0.9.1","gitCommit":"9934e11","buildDate":"2023-01-17 11:30:38","goVersion":"go1.17.13","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### What is the Kernel version?

Linux iZj6cg131cph1hzu85s506Z 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
fixed
