### ISSUE TITLE
[BUG] APPCMDS has not been inherited

### ISSUE THREAD

**Issue by YTGhost** [sealerio/sealer#1995]
### What happen?

First I use `sealer build -f Kubefile -t kubernetes-nginx:v1 .` to build a Sealer Image
```
FROM docker.io/sealerio/kubernetes:v1-22-15-sealerio-2
APP nginx local://install.yaml
APPCMDS nginx ["kubectl apply -f install.yaml"]
LAUNCH ["calico", "nginx"]
```
Use `sealer inspect localhost/kubernetes-nginx:v1`, we can see the APPCMDS content.
```
"launch": {
        "app_names": [
            "calico",
            "nginx"
        ],
        "appConfigs": [
            {
                "name": "nginx",
                "launch": {
                    "cmds": [
                        "kubectl apply -f install.yaml"
                    ]
                }
            }
        ]
    },
```
Then I build a Sealer Image that from `localhost/kubernetes-nginx:v1`
```
FROM localhost/kubernetes-nginx:v1
APP busybox local://install.yaml
APPCMDS busybox ["kubectl apply -f install.yaml"]
LAUNCH ["calico", "nginx", "busybox"]
```
Use `sealer inspect sealer inspect localhost/kubernetes-nginx:v2`, we can not find the nginx APPCMDS content.
```
"launch": {
        "app_names": [
            "calico",
            "nginx",
            "busybox"
        ],
        "appConfigs": [
            {
                "name": "busybox",
                "launch": {
                    "cmds": [
                        "kubectl apply -f install.yaml"
                    ]
                }
            }
        ]
    },
```

### What you expected to happen?

APPCMDS should be inherited and retained, and can also be overridden by the user.

### What is the version of Sealer you using?

{"gitVersion":"v0.9.1","gitCommit":"9934e11","buildDate":"2023-01-17 11:30:38","goVersion":"go1.17.13","compiler":"gc","platform":"linux/amd64"}

### What is your OS environment?

NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### What is the Kernel version?

Linux iZj6cg131cph1hzu85s506Z 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by Starnop** [comment]
I will fix it ASAP.
