### ISSUE TITLE
[BUG] failed to run sealer  alpha mount 

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2000]
### What happen?

sealer alpha mount my-app:v1

![image](https://user-images.githubusercontent.com/83740799/215974134-b5f30256-cc66-4634-a970-26009e941964.png)

### What is the version of Sealer you using?

sealer 0.9.1

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
BTW: How do we handle multi-architecture images, my suggestion is to choose the corresponding image to mount according to the machine architecture

**Comment by Starnop** [comment]
> BTW: How do we handle multi-architecture images, my suggestion is to choose the corresponding image to mount according to the machine architecture

If we can already choose the architecture intelligently, we can also provide a flag like `--platform` to allow users to decide for themselves.
