### ISSUE TITLE
[FEATURE] add ignore image list flag for supporting user to choose which one will be saved

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2007]
## Issue Description

Type: *feature request*

add flag `--ignore-image-list` to sealer build : `sealer build --ignored-image-list ignoredlist`

write ignored file:

```shell
[root@iZbp1daq0hry4n4gd6lelwZ]# cat ignoredlist 
mysql:3.2
docker.io/library/nginx:alpine
```

when build : sealer will not save those images read from  ignorelist file.

**Comment by Starnop** [comment]
@Stevent-fei Would you like to support this feature?

**Comment by Stevent-fei** [comment]
> @Stevent-fei Would you like to support this feature?

ok
