### ISSUE TITLE
[Feature] Use client-go to interact with the cluster in container in e2e test

### ISSUE THREAD

**Issue by zhy76** [sealerio/sealer#2013]
## Issue Description

Type: *feature request*

### Describe what feature you want
The previous e2e test uses ssh to obtain cluster node and pod information using the kubectl command in the container. Using client-go to get pods would better than using kubectl, kubectl would be for sure in official clusterimage,  when kubectl's version did not match, this would have an error in test stage.

In addition, if e2e test fails, pod logs cannot be obtained from the container, which makes debug very inconvenient, Especially in CI using github action, because it is like a black box. Therefore, client-go can be used to interact with the cluster in the container, and error logs can be printed for troubleshooting.
I think this is very important and helpful for e2e test.

**Comment by Starnop** [comment]
Can't help but like 👍
