### ISSUE TITLE
sealer-v0.9.0: failed to get sealer.image.extension in image

### ISSUE THREAD

**Issue by cnfzh66** [sealerio/sealer#2032]
### What happen?

[root@k8s-node01 kubefile]# sealer images
REPOSITORY                            TAG             IMAGE ID       CREATED        SIZE
docker.io/labring/kubernetes-docker   v1.20-amd64     398bb7592529   23 hours ago   547 MB
docker.io/labring/kubernetes-docker   v1.20.7-4.1.4   a1358d4696e6   34 hours ago   559 MB
docker.io/labring/helm                v3.10.3         71b74a953cdc   5 weeks ago    45.1 MB
docker.io/labring/calico              v3.22.1         29516dc98b4b   7 months ago   546 MB
[root@k8s-node01 kubefile]# sealer inspect docker.io/labring/kubernetes-docker:v1.20-amd64
Usage:
  sealer inspect [flags]

Examples:

  sealer inspect {imageName or imageID}
  sealer inspect --format '{{.OCIv1.Config.Env}}' {imageName or imageID}

Flags:
  -f, --format format   use format as a Go template to format the output
  -h, --help            help for inspect
  -t, --type type       look at the item of the specified type (container or image) and name (default "image")

Global Flags:
      --color string               set the log color mode, the possible values can be [never always] (default "always")
      --config string              config file of sealer tool (default is $HOME/.sealer.json)
  -d, --debug                      turn on debug mode
      --hide-path                  hide the log path
      --hide-time                  hide the log time
      --log-to-file                write log message to disk
  -q, --quiet                      silence the usage when fail
      --remote-logger-url string   remote logger url, if not empty, will send log to this url
      --task-name string           task name which will embedded in the remote logger header, only valid when --remote-logger-url is set

2023-02-15 11:09:57 [ERROR] [root.go:75] sealer-v0.9.0: failed to get sealer.image.extension in image docker.io/labring/kubernetes-docker:v1.20-amd64: sealer.image.extension does not exist

### What you expected to happen?

正常获取CloudRootfs

### What is the version of Sealer you using?

v0.9.0

### What is your OS environment?

Centos7.9

### What is the Kernel version?

3.10.0-1160.81.1.el7.x86_64

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by cnfzh66** [comment]
已在/data/sealos/data/default/rootfs下找到

**Comment by lusains** [comment]
I also encountered the same problem and reported this error when build image with Kubefile.

**Comment by cnfzh66** [comment]
> 

You need to use the sealerio/kubernetes of DockerHub as the basic image. If you use labring/kubernetes, this error will be reported

**Comment by lusains** [comment]
I just use the image from sealerio/kubernetes, tag & push it to private harbor (image.cestc.cn).
