### ISSUE TITLE
[help wanted] using a new progress bar SDK  to sealer scp 

### ISSUE THREAD

**Issue by kakaZhou719** [sealerio/sealer#2052]
## Issue Description

we can simply use  progress bar sdk  such as "https://github.com/schollz/progressbar" to make sealer more easier to customize  and more stable.

Type: *feature request*

**Comment by Lan-ce-lot** [comment]
I found that it was closed, is this feature still needed?

**Comment by kakaZhou719** [comment]
> 

aha, by mistake ~~

**Comment by Lan-ce-lot** [comment]
I’m palnning to work on this.

**Comment by kakaZhou719** [comment]
> I’m palnning to work on this.

👍 go ahead ~~

**Comment by Lan-ce-lot** [comment]
Is the style of the progress bar that can be like this?

![file](https://user-images.githubusercontent.com/53330071/226790687-fe3e8a9c-5ea2-4fc8-9673-d624701bf44d.gif)

**Comment by kakaZhou719** [comment]
> Is the style of the progress bar that can be like this?
> 
> ![file](https://user-images.githubusercontent.com/53330071/226790687-fe3e8a9c-5ea2-4fc8-9673-d624701bf44d.gif) [ ![file](https://user-images.githubusercontent.com/53330071/226790687-fe3e8a9c-5ea2-4fc8-9673-d624701bf44d.gif) ](https://user-images.githubusercontent.com/53330071/226790687-fe3e8a9c-5ea2-4fc8-9673-d624701bf44d.gif) [ ](https://user-images.githubusercontent.com/53330071/226790687-fe3e8a9c-5ea2-4fc8-9673-d624701bf44d.gif)

oh, its cool, looks good ~
