### ISSUE TITLE
0.9.1

### ISSUE THREAD

**Issue by fi-ecavc** [sealerio/sealer#2059]
### What happen?

We deploy the k8s environment on 3 cloud hosts, using sealer version 0.9.1 to execute, the execution script is: sealer run docker.io/sealerio/kubernetes:v1.22.15 --masters 172.30.37.116 --nodes 172.30.37.117, 172.30.37.118 --passwd vcs, an error occurred

use journalctl -xe ：

-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished shutting down.
Feb 24 09:45:02 dev10 systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
Feb 24 09:45:02 dev10 systemd[12359]: Failed at step EXEC spawning /usr/bin/kubelet: No such file or directory
-- Subject: Process /usr/bin/kubelet could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/bin/kubelet could not be executed and failed.
--
-- The error number returned by this process is 2.
Feb 24 09:45:02 dev10 systemd[1]: kubelet.service: main process exited, code=exited, status=203/EXEC
Feb 24 09:45:02 dev10 systemd[1]: Unit kubelet.service entered failed state.
Feb 24 09:45:02 dev10 systemd[1]: kubelet.service failed.
Feb 24 09:45:12 dev10 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Feb 24 09:45:12 dev10 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.

### Relevant log output?

```Shell
+ chmod a+x /usr/bin
+ chmod a+x /usr/bin/docker
+ chmod a+x /usr/bin/dockerd
+ systemctl enable docker.service
+ systemctl restart docker.service
+ cp /var/lib/sealer/data/my-cluster/rootfs/scripts/../etc/daemon.json /etc/docker
+ [[ -n '' ]]
+ disable_selinux
+ '[' -s /etc/selinux/config ']'
+ grep SELINUX=enforcing /etc/selinux/config
+ systemctl daemon-reload
+ systemctl restart docker.service
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
2023-02-24 09:57:40 [INFO] [remove_container.go:66] 21e3e5b75aa04c3341699be7ee0ae1d3187b74101f97217b76e7084642e8b3b6
```

### What is your OS environment?

centos7.9 

### What is the Kernel version?

Linux dev10 5.4.232-1.el7.elrepo.x86_64 #1 SMP Tue Feb 21 16:18:52 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by fi-ecavc** [comment]
{
  "experimental": true,
  "oom-score-adjust": -1000,
  "max-concurrent-downloads": 20,
  "log-driver": "json-file",
  "log-level": "warn",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "exec-opts": [
    "native.cgroupdriver=systemd"
  ],
  "insecure-registries": ["0.0.0.0/0", "::/0"],
  "storage-driver": "overlay2",
  "storage-opts":["overlay2.override_kernel_check=true"],
  "live-restore": true,
  "data-root": "/var/lib/docker"
}
~
"/etc/docker/daemon.json" [noeol] 19L, 457C

**Comment by fi-ecavc** [comment]
Could it be a "live-restore": true question? It should be false

**Comment by fi-ecavc** [comment]
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2023-02-24 11:29:03 CST; 23s ago
     Docs: https://docs.docker.com
  Process: 15447 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 15447 (code=exited, status=1/FAILURE)

Feb 24 11:29:03 dev10 dockerd[15447]: time="2023-02-24T11:29:03.383726524+08:00" level=warning msg="Running experimental build"
Feb 24 11:29:03 dev10 dockerd[15447]: time="2023-02-24T11:29:03.409917150+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Feb 24 11:29:03 dev10 dockerd[15447]: time="2023-02-24T11:29:03.411002328+08:00" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
Feb 24 11:29:03 dev10 dockerd[15447]: time="2023-02-24T11:29:03.429433391+08:00" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 24 11:29:03 dev10 dockerd[15447]: time="2023-02-24T11:29:03.429451596+08:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Feb 24 11:29:03 dev10 dockerd[15447]: time="2023-02-24T11:29:03.515372700+08:00" level=fatal msg="Error starting cluster component: --live-restore daemon configuration is incompatible with swarm mode"
Feb 24 11:29:03 dev10 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Feb 24 11:29:03 dev10 systemd[1]: Failed to start Docker Application Container Engine.
Feb 24 11:29:03 dev10 systemd[1]: Unit docker.service entered failed state.
Feb 24 11:29:03 dev10 systemd[1]: docker.service failed.

**Comment by kakaZhou719** [comment]
hi @fi-ecavc , pls use our official image list here:  http://sealer.cool/docs/sealer-images/cluster-images.html#k8s-cluster-image-list.   if you have any questions, feel free to contact us .

**Comment by fi-ecavc** [comment]
sealer run docker.io/sealerio/kubernetes:v1.22.15   --masters 172.30.37.116    --nodes 172.30.37.117,172.30.37.118    --passwd vcs
 uname -a
Linux dev10 5.4.232-1.el7.elrepo.x86_64 #1 SMP Tue Feb 21 16:18:52 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fi-ecavc** [comment]
> hi @fi-ecavc , pls use our official image list here: http://sealer.cool/docs/sealer-images/cluster-images.html#k8s-cluster-image-list. if you have any questions, feel free to contact us .
warning msg="Your kernel does not support cgroup blkio weight"。Is there something wrong with our kernel?
fatal msg="Error starting cluster component: --live-restore daemon configuration is incompatible with swarm mode"，Does Seaver's communication mechanism use Swarm Mode? The --live-restore parameter is contradictory, and the hint is already clear.
