### ISSUE TITLE
Support sealer rollback

### ISSUE THREAD

**Issue by wizardlyk** [sealerio/sealer#2102]
## Issue Description

Type: *feature request*

### Describe what feature you want
Rollback kubernetes cluster by using sealer rollback --flags

### Additional context
Corresponding to the upgrade function；Distribute old version k8s material by sealer。

rollback cmd:
```
sealer rollback docker.io/sealerio/kubernetes:v1.20.4
```

**Comment by kakaZhou719** [comment]
Already supported .https://github.com/sealerio/sealer/pull/2115
