### ISSUE TITLE
NodePort 只有pod 所在的物理机节点能通，其他节点不通。sealer 部署的k8s 1.22.15版本

### ISSUE THREAD

**Issue by 710210668** [sealerio/sealer#2143]
### What happen?
svc 的流量策略都是：Cluster 模式
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
请求pod 所在的物理机，返回200

`[root@master1 test]# curl -iv 10.203.98.71:30013
* About to connect() to 10.203.98.71 port 30013 (#0)
*   Trying 10.203.98.71...
* Connected to 10.203.98.71 (10.203.98.71) port 30013 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.203.98.71:30013
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK

`
其他节点没响应
[root@master1 test]# curl 10.203.98.72:30013
curl: (7) Failed connect to 10.203.98.72:30013; Connection timed out

### What is the version of Sealer you using?
sealer 0.9
_No response_

### What is your OS environment?

centos 7.9

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by cubxxw** [comment]
这和sealos有关系嘛👀 
检查一下 Kubernetes 的 service 信息。
在其他节点上用 nc -zv master1 30013 校验一下。不可用的话可能是防火墙的原因，或者是网络配置原因

**Comment by 710210668** [comment]
防火墙sealer 部署的时候会设置关闭的，看过防火墙，都没有启用

**Comment by 710210668** [comment]
把pod 调度到别的节点，别的节点的ip + NodePort 端口就能访问了，不知道为啥，没有思路，这样的话应该可以排除节点之间的防火墙问题的

**Comment by Stevent-fei** [comment]
@710210668 Can you show the contents of this file? `/var/lib/sealer/data/my-cluster/rootfs/applications/custom-resources.yaml`

**Comment by 710210668** [comment]
改成ipip可以了，谢谢

**Comment by Stevent-fei** [comment]
This issue has been resolved i will close it.
