### ISSUE TITLE
Compress the cache registry directory

### ISSUE THREAD

**Issue by clcc2019** [sealerio/sealer#2164]
### What happen?

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/46099295/229708205-e894c78b-832a-42d4-b1d8-1adb5b957525.png">
Does the new version not pack and compress the image cache, there are too many small files

### What is the version of Sealer you using?

0.9.3

### What is your OS environment?

debian 10

### What is the Kernel version?

4.19.0-23-amd64

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by kakaZhou719** [comment]
@clcc2019 ，yes, registry data is not compressed. Actually ,we are planning to do it in the next sealer version. more to see https://github.com/sealerio/sealer/issues/2100.
