### ISSUE TITLE
支持对镜像设置别名

### ISSUE THREAD

**Issue by fangzhengjin** [sealerio/sealer#2182]
## Issue Description

Type: *feature request*

### Describe what feature you want

sealer在自己构建集群镜像时, 因为GFW的原因, 部分图像无法拉取, 如果使用第三方仓库拉取, imageList中的图像名称就需要修改, 导致使用该镜像部署集群时, 找不到yaml中指定的镜像名称
是否可以考虑在imageList中加入别名配置的方式来避免这种问题, 例如: 原镜像地址(部署集群镜像内置仓库使用的镜像名称)=别名地址(构建集群镜像实际pull地址)

**Comment by clcc2019** [comment]
不需要关注别名，可以这样定义：

**Comment by fangzhengjin** [comment]
也就是说, sealer会遍历所有yaml找到镜像地址包括helm的chart, 替换前缀为`sea.hub:5000`是吗? 那如果我在部署时希望使用自己搭建的镜像仓库而不是`sea.hub:5000`应该怎么操作呢?

**Comment by Starnop** [comment]
@fangzhengjin maybe use Kyverno will help you to realize the above capabilities.

FYI.  http://sealer.cool/docs/advanced/use-sealer-image-offline.html#how-to-build-kyverno-appimage
