### ISSUE TITLE
Use 'uname -n' instead of 'hostname'

### ISSUE THREAD

**Issue by Daz-3ux** [sealerio/sealer#2194]
## Issue Description

Type: *feature request*

### Describe what feature you want
When setting up a node on the Arch Linux virtual machine, I encountered a problem where the 'hostname' command was not found. After running 'sudo pacman -S inetutils', everything worked fine. Perhaps we can use 'uname -n' as a replacement for 'hostname' to achieve higher universality.

### Additional context
On the next reboot, systemd-hostname will read the /etc/hostname and set the hostname. So `uname -n` seems have no difference with hostname(besides more general).

I can handle this issue if it makes sense : )

**Comment by Daz-3ux** [comment]
error agian👀
```
masterdaz# sealer run kubernetes:v1.19.8  \
  --masters 192.168.122.8 \
  --nodes 192.168.122.9,192.168.122.10 --passwd xx
2023-04-22 14:53:46 [INFO] [local.go:288] Start to create a new cluster: master [192.168.122.8], worker [192.168.122.9 1
92.168.122.10]
copying files to 192.168.122.10: 32/32
copying files to 192.168.122.9: 32/32
Error: failed to init master0 exec remote cmd failed, hostname exit status 127
```

**Comment by kakaZhou719** [comment]
@Daz-3ux , nice issue,  it sounds good to me.  we should get the hostname value from where it was registered.  if `uname -n` meet our request , feel free pr your code 😀
