### ISSUE TITLE
cluster upgrade not working

### ISSUE THREAD

**Issue by clcc2019** [sealerio/sealer#2244]
### What happen?

<img width="1511" alt="image" src="https://github.com/sealerio/sealer/assets/46099295/b5cd2478-3c70-4ac3-bd1a-0f0fea94ba86">

### What is the version of Sealer you using?

v0.10

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by clcc2019** [comment]
Is the upgrade function removed?

**Comment by kakaZhou719** [comment]
@clcc2019 ， it not removed. but upgrade action also need special sealer image to do real upgrade

**Comment by clcc2019** [comment]
> @clcc2019 ， it not removed. but upgrade action also need special sealer image to do real upgrade

how do change the mirror image

**Comment by clcc2019** [comment]
@kakaZhou719 The previous version was implemented by code, why do we need mirror support now, I think it has become complicated

**Comment by clcc2019** [comment]
I need to implement it through Plugin?

**Comment by kakaZhou719** [comment]
> I need to implement it through Plugin?

yes, you need to build your own upgrade image with  upgrade plugin. FYI: http://sealer.cool/docs/concept/clusterfile.html#plugin-api
