### ISSUE TITLE
Can I maintain the application image cache separately

### ISSUE THREAD

**Issue by clcc2019** [sealerio/sealer#606]
Can I maintain the application image cache separately？
Delete, add images

**Comment by fanux** [comment]
If you want to add a image to CloudImage, recommend way is using build, like lite build.
Delete I think we don't have a solution now, do you have any idea about the design?

**Comment by kakaZhou719** [comment]
@clcc2019 ，we can use `sealer build -t app:v1 --base=false` to build a cloud image without rootfs layer.
