### ISSUE TITLE
About development of sealer upgrade command

### ISSUE THREAD

**Issue by shy-Xu** [sealerio/sealer#620]
i have learned about two relative command: "kubeadm upgrade" and "helm upgrade". the former focus on upgrade of nodes,that is,to a new version of k8s, while the later focus on upgrade of applications. that is, to a new version of image(chart). which one do we prefer "sealer upgrade" to do?

**Comment by shy-Xu** [comment]
Do we want "sealer upgrade" do something as the command "sealos upgrade" do?

**Comment by allencloud** [comment]
sealer upgrade has already been supported, closing this.
