### ISSUE TITLE
sealer deployment process is phased

### ISSUE THREAD

**Issue by lllwan** [sealerio/sealer#823]
## Issue Description

Type: *feature request*

**Comment by kakaZhou719** [comment]
@lllwan ，do you mean copy the rootfs  files incrementally?

**Comment by lllwan** [comment]
> @lllwan ，do you mean copy the rootfs files incrementally?

In the process, due to some external environment reasons, sealer's deployment process has errors. When chong'xin tries, sealer will copy rootfs again, which takes a long time. We spent a day troubleshooting problems, and at least 70% of the time spent in this day was wasted on the repeated copy of rootfs. My idea is: implement in stages. For example, copy rootfs is a stage, initialization is a stage, and deployment cluster is a stage. Users can choose to start from scratch or a certain stage.

**Comment by bxy4543** [comment]
[Nydus](https://github.com/sealerio/applications/tree/main/nydus) can help sealer to improve image distribution performance
